## Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
%matplotlib inline

## Create functions for assigning timestamps to signals

Data arrives in packets of 64 (ecg) or 32 (pleth) with a single timestamp. Therefore, each array needs to manually be assigned individual timestamps.

In [2]:
def expand_pleth_times(timestamp):
    x = pd.date_range(timestamp, periods=32,freq='8L',closed="left")
    return x

def expand_ecg_times(timestamp):
    x = pd.date_range(timestamp, periods=64,freq='4L',closed="left")
    return x

## Load and Clean Signals

* Load physio data
* Cleaning:
    * Timestamps/timezones -- physio data CSVs are time local (EST) but alamrs come with UTC offset.
        * Bokeh visualizer and pandas treat times as UTC, so must explicitly declare TZ intent.
    * Merge duplicate timestamp entries into 1 row

In [3]:
fname = '../../original_data/5-25-5-26'
physio_df = pd.read_json(fname, lines=True)

physio_df.set_index("timestamp",inplace=True)
physio_df.tz_localize('Etc/GMT+4',copy=False)
physio_df[['Heart Rate','Respiration Rate','SpO2','qos']] = physio_df[['Heart Rate','Respiration Rate','SpO2','qos']].apply(pd.to_numeric,errors='coerce')

In [4]:
physio_df

,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,alarms,qos
timestamp,,,,,,,,,
2017-05-24 23:56:16.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,NaN,None,1
2017-05-24 23:56:17.016000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,NaN,None,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,NaN,None,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,96.7,None,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,1
2017-05-24 23:56:18.712000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:17.272000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,NaN,None,1
2017-05-24 23:56:17.528000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,NaN,None,1
2017-05-24 23:56:17.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,NaN,None,1
2017-05-24 23:56:18.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,NaN,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,NaN,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,96.5,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:18.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,NaN,None,1
2017-05-24 23:56:18.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,NaN,None,1
2017-05-24 23:56:18.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,NaN,None,1
2017-05-24 23:56:19.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,NaN,None,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,NaN,None,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,96.3,None,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,1
2017-05-24 23:56:20.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:19.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,NaN,None,1
2017-05-24 23:56:19.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,NaN,None,1
2017-05-24 23:56:19.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,NaN,None,1
2017-05-24 23:56:20.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,NaN,None,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,NaN,None,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,96.0,None,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,1
2017-05-24 23:56:21.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
...,...,...,...,...,...,...,...,...,...
2017-05-26 23:56:06.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:06.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:05.584000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.096000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.352000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:07.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:06.608000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.120000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.376000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:09.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:07.632000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.144000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.400000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:08.656000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:09.168000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:09.424000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0

In [5]:
'''
Collapse multiple entries for a single timestamp to one row.

Example, this:

        value_1 value_2 value_3
time_1    1        1      NaN
time_1    NaN     NaN      1

Becomes:
        value_1 value_2 value_3
time_1     1       1       1

'''
merged_df = physio_df.groupby("timestamp").first()
merged_df

,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,alarms,qos
timestamp,,,,,,,,,
2017-05-24 23:56:16.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,NaN,None,1
2017-05-24 23:56:17.016000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,NaN,None,1
2017-05-24 23:56:17.272000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,NaN,None,1
2017-05-24 23:56:17.528000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,NaN,None,1
2017-05-24 23:56:17.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,NaN,None,1
2017-05-24 23:56:18.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,NaN,None,1
2017-05-24 23:56:18.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,NaN,None,1
2017-05-24 23:56:18.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,NaN,None,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.7,None,1
2017-05-24 23:56:18.712000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:18.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,NaN,None,1
2017-05-24 23:56:19.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,NaN,None,1
2017-05-24 23:56:19.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,NaN,None,1
2017-05-24 23:56:19.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,NaN,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.5,None,1
2017-05-24 23:56:19.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,NaN,None,1
2017-05-24 23:56:20.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,NaN,None,1
2017-05-24 23:56:20.344000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2408, 2338, 2260, 2176, 2087, 1997, 1909, 183...",NaN,NaN,None,1
2017-05-24 23:56:20.600000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1113, 1098, 1076, 1050, 1021, 988, 955, 925, ...",NaN,NaN,None,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.3,None,1
2017-05-24 23:56:20.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:20.856000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2574, 2553, 2526, 2492, 2451, 2408, 2361, 230...",NaN,NaN,None,1
2017-05-24 23:56:21.112000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1279, 1263, 1246, 1227, 1243, 1276, 1281, 127...",NaN,NaN,None,1
2017-05-24 23:56:21.368000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2749, 2771, 2784, 2789, 2785, 2775, 2761, 274...",NaN,NaN,None,1
2017-05-24 23:56:21.624000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1581, 1564, 1547, 1529, 1511, 1492, 1472, 145...",NaN,NaN,None,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.0,None,1
2017-05-24 23:56:21.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:21.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2535, 2591, 2629, 2655, 2677, 2693, 2702, 270...",NaN,NaN,None,1
2017-05-24 23:56:22.136000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1609, 1588, 1570, 1552, 1535, 1518, 1501, 148...",NaN,NaN,None,1
2017-05-24 23:56:22.392000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2149, 2230, 2307, 2374, 2431, 2477, 251...",NaN,NaN,None,1
...,...,...,...,...,...,...,...,...,...
2017-05-26 23:56:04.304000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:04.560000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:04.816000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:04.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:04.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:05.072000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.328000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.584000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.904000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:06.096000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.352000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.608000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:07.120000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.376000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.632000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:07.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:08.144000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.400000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.656000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:09.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:09.168000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:09.424000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0

Drop machine generated alarms, since we are going to use the manually annotated alarms.

In [6]:
cleaned_df = merged_df.drop(['alarms'],axis = 1)
cleaned_df

,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,qos
timestamp,,,,,,,,
2017-05-24 23:56:16.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,NaN,1
2017-05-24 23:56:17.016000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,NaN,1
2017-05-24 23:56:17.272000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,NaN,1
2017-05-24 23:56:17.528000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,NaN,1
2017-05-24 23:56:17.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,NaN,1
2017-05-24 23:56:18.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,NaN,1
2017-05-24 23:56:18.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,NaN,1
2017-05-24 23:56:18.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,NaN,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.7,1
2017-05-24 23:56:18.712000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,1
2017-05-24 23:56:18.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,NaN,1
2017-05-24 23:56:19.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,NaN,1
2017-05-24 23:56:19.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,NaN,1
2017-05-24 23:56:19.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,NaN,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.5,1
2017-05-24 23:56:19.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,NaN,1
2017-05-24 23:56:20.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,NaN,1
2017-05-24 23:56:20.344000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2408, 2338, 2260, 2176, 2087, 1997, 1909, 183...",NaN,NaN,1
2017-05-24 23:56:20.600000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1113, 1098, 1076, 1050, 1021, 988, 955, 925, ...",NaN,NaN,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.3,1
2017-05-24 23:56:20.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,1
2017-05-24 23:56:20.856000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2574, 2553, 2526, 2492, 2451, 2408, 2361, 230...",NaN,NaN,1
2017-05-24 23:56:21.112000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1279, 1263, 1246, 1227, 1243, 1276, 1281, 127...",NaN,NaN,1
2017-05-24 23:56:21.368000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2749, 2771, 2784, 2789, 2785, 2775, 2761, 274...",NaN,NaN,1
2017-05-24 23:56:21.624000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1581, 1564, 1547, 1529, 1511, 1492, 1472, 145...",NaN,NaN,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.0,1
2017-05-24 23:56:21.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,1
2017-05-24 23:56:21.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2535, 2591, 2629, 2655, 2677, 2693, 2702, 270...",NaN,NaN,1
2017-05-24 23:56:22.136000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1609, 1588, 1570, 1552, 1535, 1518, 1501, 148...",NaN,NaN,1
2017-05-24 23:56:22.392000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2149, 2230, 2307, 2374, 2431, 2477, 251...",NaN,NaN,1
...,...,...,...,...,...,...,...,...
2017-05-26 23:56:04.304000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:04.560000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:04.816000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:04.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:04.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,0
2017-05-26 23:56:05.072000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:05.328000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:05.584000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:05.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:05.904000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:06.096000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:06.352000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:06.608000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:06.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:06.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:07.120000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:07.376000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:07.632000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:07.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:07.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,0
2017-05-26 23:56:08.144000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:08.400000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:08.656000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:08.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:09.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,0
2017-05-26 23:56:09.168000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:09.424000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0

In [7]:
file_name = '../../clean_data/Model_Sherry/5-25-5-26_clean_del_alarm.csv'
cleaned_df.to_csv(file_name, encoding='utf-8', index=True)

In [8]:
clean_df = pd.read_csv(file_name,parse_dates=[0])

In [9]:
clean_df

,timestamp,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,qos
0,2017-05-25 03:56:16.760,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,NaN,1
1,2017-05-25 03:56:17.016,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,NaN,1
2,2017-05-25 03:56:17.272,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,NaN,1
3,2017-05-25 03:56:17.528,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,NaN,1
4,2017-05-25 03:56:17.784,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,NaN,1
5,2017-05-25 03:56:18.040,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,NaN,1
6,2017-05-25 03:56:18.296,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,NaN,1
7,2017-05-25 03:56:18.552,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,NaN,1
8,2017-05-25 03:56:18.680,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,NaN,96.7,1
9,2017-05-25 03:56:18.712,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,1
10,2017-05-25 03:56:18.808,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,NaN,1
11,2017-05-25 03:56:19.064,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,NaN,1
12,2017-05-25 03:56:19.320,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,NaN,1
13,2017-05-25 03:56:19.576,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,NaN,1
14,2017-05-25 03:56:19.736,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,NaN,96.5,1
15,2017-05-25 03:56:19.832,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,NaN,1
16,2017-05-25 03:56:20.088,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,NaN,1
17,2017-05-25 03:56:20.344,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2408, 2338, 2260, 2176, 2087, 1997, 1909, 183...",NaN,NaN,1
18,2017-05-25 03:56:20.600,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1113, 1098, 1076, 1050, 1021, 988, 955, 925, ...",NaN,NaN,1
19,2017-05-25 03:56:20.728,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,NaN,96.3,1
20,2017-05-25 03:56:20.760,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,1
21,2017-05-25 03:56:20.856,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2574, 2553, 2526, 2492, 2451, 2408, 2361, 230...",NaN,NaN,1
22,2017-05-25 03:56:21.112,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1279, 1263, 1246, 1227, 1243, 1276, 1281, 127...",NaN,NaN,1
23,2017-05-25 03:56:21.368,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2749, 2771, 2784, 2789, 2785, 2775, 2761, 274...",NaN,NaN,1
24,2017-05-25 03:56:21.624,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1581, 1564, 1547, 1529, 1511, 1492, 1472, 145...",NaN,NaN,1
25,2017-05-25 03:56:21.752,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,NaN,96.0,1
26,2017-05-25 03:56:21.784,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,1
27,2017-05-25 03:56:21.880,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2535, 2591, 2629, 2655, 2677, 2693, 2702, 270...",NaN,NaN,1
28,2017-05-25 03:56:22.136,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1609, 1588, 1570, 1552, 1535, 1518, 1501, 148...",NaN,NaN,1
29,2017-05-25 03:56:22.392,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2149, 2230, 2307, 2374, 2431, 2477, 251...",NaN,NaN,1
...,...,...,...,...,...,...,...,...,...
761405,2017-05-27 03:56:04.304,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761406,2017-05-27 03:56:04.560,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761407,2017-05-27 03:56:04.816,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761408,2017-05-27 03:56:04.880,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
761409,2017-05-27 03:56:04.912,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,0
761410,2017-05-27 03:56:05.072,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761411,2017-05-27 03:56:05.328,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761412,2017-05-27 03:56:05.584,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761413,2017-05-27 03:56:05.840,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761414,2017-05-27 03:56:05.904,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
761415,2017-05-27 03:56:06.096,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761416,2017-05-27 03:56:06.352,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761417,2017-05-27 03:56:06.608,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761418,2017-05-27 03:56:06.864,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761419,2017-05-27 03:56:06.928,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
761420,2017-05-27 03:56:07.120,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761421,2017-05-27 03:56:07.376,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761422,2017-05-27 03:56:07.632,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761423,2017-05-27 03:56:07.888,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761424,2017-05-27 03:56:07.952,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
761425,2017-05-27 03:56:07.984,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,0
761426,2017-05-27 03:56:08.144,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761427,2017-05-27 03:56:08.400,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761428,2017-05-27 03:56:08.656,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761429,2017-05-27 03:56:08.912,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761430,2017-05-27 03:56:08.976,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
761431,2017-05-27 03:56:09.008,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,0
761432,2017-05-27 03:56:09.168,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761433,2017-05-27 03:56:09.424,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
761434,2017-05-27 03:56:10.000,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0

In [10]:
clean_df.set_index("timestamp",inplace=True)
clean_df

,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,qos
timestamp,,,,,,,,
2017-05-25 03:56:16.760,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,NaN,1
2017-05-25 03:56:17.016,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,NaN,1
2017-05-25 03:56:17.272,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,NaN,1
2017-05-25 03:56:17.528,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,NaN,1
2017-05-25 03:56:17.784,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,NaN,1
2017-05-25 03:56:18.040,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,NaN,1
2017-05-25 03:56:18.296,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,NaN,1
2017-05-25 03:56:18.552,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,NaN,1
2017-05-25 03:56:18.680,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,NaN,96.7,1
2017-05-25 03:56:18.712,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,1
2017-05-25 03:56:18.808,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,NaN,1
2017-05-25 03:56:19.064,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,NaN,1
2017-05-25 03:56:19.320,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,NaN,1
2017-05-25 03:56:19.576,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,NaN,1
2017-05-25 03:56:19.736,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,NaN,96.5,1
2017-05-25 03:56:19.832,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,NaN,1
2017-05-25 03:56:20.088,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,NaN,1
2017-05-25 03:56:20.344,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2408, 2338, 2260, 2176, 2087, 1997, 1909, 183...",NaN,NaN,1
2017-05-25 03:56:20.600,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1113, 1098, 1076, 1050, 1021, 988, 955, 925, ...",NaN,NaN,1
2017-05-25 03:56:20.728,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,NaN,96.3,1
2017-05-25 03:56:20.760,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,1
2017-05-25 03:56:20.856,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2574, 2553, 2526, 2492, 2451, 2408, 2361, 230...",NaN,NaN,1
2017-05-25 03:56:21.112,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1279, 1263, 1246, 1227, 1243, 1276, 1281, 127...",NaN,NaN,1
2017-05-25 03:56:21.368,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2749, 2771, 2784, 2789, 2785, 2775, 2761, 274...",NaN,NaN,1
2017-05-25 03:56:21.624,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1581, 1564, 1547, 1529, 1511, 1492, 1472, 145...",NaN,NaN,1
2017-05-25 03:56:21.752,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,NaN,96.0,1
2017-05-25 03:56:21.784,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,1
2017-05-25 03:56:21.880,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2535, 2591, 2629, 2655, 2677, 2693, 2702, 270...",NaN,NaN,1
2017-05-25 03:56:22.136,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1609, 1588, 1570, 1552, 1535, 1518, 1501, 148...",NaN,NaN,1
2017-05-25 03:56:22.392,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2149, 2230, 2307, 2374, 2431, 2477, 251...",NaN,NaN,1
...,...,...,...,...,...,...,...,...
2017-05-27 03:56:04.304,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:04.560,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:04.816,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:04.880,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
2017-05-27 03:56:04.912,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,0
2017-05-27 03:56:05.072,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:05.328,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:05.584,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:05.840,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:05.904,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
2017-05-27 03:56:06.096,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:06.352,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:06.608,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:06.864,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:06.928,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
2017-05-27 03:56:07.120,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:07.376,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:07.632,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:07.888,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:07.952,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
2017-05-27 03:56:07.984,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,0
2017-05-27 03:56:08.144,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:08.400,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:08.656,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:08.912,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:08.976,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0
2017-05-27 03:56:09.008,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,NaN,0
2017-05-27 03:56:09.168,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:09.424,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-27 03:56:10.000,"{'Respiration Rate': None, 'etCO2': None}",NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,NaN,0

## Load and Clean Alarms

* Load alarm data
* Cleaning:
    * Timestamps/timezones

In [11]:
alarms_fname = '../../original_data/5-25-5-26-ecg-alarms.csv'
alarms_df = pd.read_csv(alarms_fname,parse_dates=[0])
alarms_df = alarms_df.set_index("timestamp").tz_localize("UTC").tz_convert('Etc/GMT+4')
alarms_df

                                                                     alarm_type
timestamp
2017-05-25 05:52:54.992000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 05:53:51.312000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 05:58:09.360000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 05:58:10.384000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 06:00:32.720000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 06:00:55.720000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 06:09:29.296000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 09:50:49.584000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 09:56:07.024000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 09:56:08.016000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 10:00:40.400000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 10:24:02.256000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 16:55:49.960000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 22:42:52.264000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 22:46:46.760000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 22:50:12.584000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 23:41:58.496000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 23:45:18.176000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 00:58:06.592000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:18:20-04:00         Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:25:06.560000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:28:29.312000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:33:53.888000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:43:18.112000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 02:10:39.584000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)

## Putting it together

* Pipeline:
    1. Choose an alarm
    2. Apply it to the orignial dataset
    3. Unpack the dictionary containing non-invasive blood pressure values

In [12]:
# merged = pd.merge(left=cleaned_df, left_index=True,
#                   right=alarms_df, right_index=True,
#                   how='outer')
# merged

In [13]:
# merged[["diastolic_bp","mean_bp","systolic_bp"]] = merged["Non-invasive Blood Pressure"].apply(pd.Series).apply(pd.to_numeric,errors='ignore')
# merged

Slice dataframe based on window of time around alarm (isolated_physio_df)

In [14]:
alarms = alarms_df.index.to_pydatetime()
alarms

array([ datetime.datetime(2017, 5, 25, 5, 52, 54, 992000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 5, 53, 51, 312000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 5, 58, 9, 360000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 5, 58, 10, 384000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 6, 0, 32, 720000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 6, 0, 55, 720000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 6, 9, 29, 296000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 9, 50, 49, 584000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 9, 56, 7, 24000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 9, 56, 8, 16000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 10, 0, 40, 400000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 10, 24, 2, 256000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 16, 55, 49, 960000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 22, 42, 52, 264000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 22, 46, 46, 760000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 22, 50, 12, 584000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 23, 41, 58, 496000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 23, 45, 18, 176000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 0, 58, 6, 592000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 18, 20, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 25, 6, 560000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 28, 29, 312000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 33, 53, 888000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 43, 18, 112000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 2, 10, 39, 584000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>)], dtype=object)

In [15]:
len(alarms)

25

In [16]:
alarm = alarms[0]
alarm

datetime.datetime(2017, 5, 25, 5, 52, 54, 992000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>)

In [17]:
sliced_df = cleaned_df[alarm-pd.Timedelta("500 seconds"):alarm]
len(sliced_df)

2441

In [18]:
sliced_df

,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,qos
timestamp,,,,,,,,
2017-05-25 05:44:35.216000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.065000000000004, -0.08000000000000501, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2996, 2986, 2966, 2937, 2901, 2862, 2821, 277...",NaN,NaN,1
2017-05-25 05:44:35.472000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.025000000000005, -0.020000000000010003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1775, 1779, 1780, 1777, 1769, 1757, 1741, 172...",NaN,NaN,1
2017-05-25 05:44:35.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1218, 1210, 1201, 1196, 1193, 1186, 1177, 116...",NaN,NaN,1
2017-05-25 05:44:35.792000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,16.0,98.5,1
2017-05-25 05:44:35.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.034999999999989005, 0.009999999999990001, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2972, 2980, 2978, 2967, 2948, 2931, 2913, 288...",NaN,NaN,1
2017-05-25 05:44:36.240000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1713, 1713, 1714, 1713, 1710, 1704, 1695, 168...",NaN,NaN,1
2017-05-25 05:44:36.496000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1163, 1150, 1138, 1127, 1116, 1105, 1094, 108...",NaN,NaN,1
2017-05-25 05:44:36.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.035000000000003, -0.045000000000008006, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2922, 2955, 2981, 2998, 3005, 3002, 2990, 297...",NaN,NaN,1
2017-05-25 05:44:36.816000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,16.0,98.5,1
2017-05-25 05:44:37.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.15000000000000502, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1728, 1724, 1723, 1723, 1722, 1721, 1719, 171...",NaN,NaN,1
2017-05-25 05:44:37.264000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.160000000000003, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1179, 1167, 1156, 1146, 1136, 1127, 1119, 111...",NaN,NaN,1
2017-05-25 05:44:37.520000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.135000000000005, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2352, 2495, 2622, 2731, 2810, 2868, 2922, 296...",NaN,NaN,1
2017-05-25 05:44:37.776000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.19500000000000703, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1850, 1812, 1783, 1762, 1749, 1741, 1738, 173...",NaN,NaN,1
2017-05-25 05:44:37.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,16.0,98.5,1
2017-05-25 05:44:38.032000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.23999999999999402, 0.20999999999999303, 0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1298, 1274, 1256, 1242, 1225, 1217, 1213, 120...",NaN,NaN,1
2017-05-25 05:44:38.288000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.14500000000001, -0.1400...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1261, 1387, 1537, 1704, 1881, 2059, 2230, 237...",NaN,NaN,1
2017-05-25 05:44:38.544000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.035000000000003, 0.22999999999998902, 0.69...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2322, 2253, 2177, 2101, 2030, 1966, 1911, 186...",NaN,NaN,1
2017-05-25 05:44:38.800000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.20999999999999303, 0.22999999999998902, 0.2...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1526, 1495, 1465, 1436, 1408, 1381, 1360, 134...",NaN,NaN,1
2017-05-25 05:44:38.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,16.0,98.4,1
2017-05-25 05:44:39.056000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1074, 1078, 1096, 1136, 1204, 1303, 1433, 158...",NaN,NaN,1
2017-05-25 05:44:39.312000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2606, 2541, 2470, 2393, 2320, 2249, 2170, 209...",NaN,NaN,1
2017-05-25 05:44:39.568000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.049999999999990004, 0.06499999999999001, 0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1625, 1598, 1569, 1539, 1508, 1477, 1445, 141...",NaN,NaN,1
2017-05-25 05:44:39.824000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.140000000000007, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1064, 1049, 1039, 1032, 1024, 1024, 1038, 107...",NaN,NaN,1
2017-05-25 05:44:39.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,16.0,98.4,1
2017-05-25 05:44:40.080000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09000000000001, -0.09000000000001, -0.0900...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2938, 2896, 2851, 2803, 2750, 2689, 2620, 254...",NaN,NaN,1
2017-05-25 05:44:40.336000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.040000000000006, -0.030000000000008003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1712, 1701, 1688, 1671, 1650, 1627, 1602, 157...",NaN,NaN,1
2017-05-25 05:44:40.592000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.140000000000007, -0.140...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1112, 1105, 1097, 1088, 1077, 1064, 1055, 104...",NaN,NaN,1
2017-05-25 05:44:40.848000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.08000000000000501, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3034, 3017, 2994, 2964, 2928, 2888, 2844, 279...",NaN,NaN,1
2017-05-25 05:44:40.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,76.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,16.0,98.3,1
2017-05-25 05:44:41.104000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1754, 1752, 1747, 1738, 1725, 1712, 1698, 168...",NaN,NaN,1
...,...,...,...,...,...,...,...,...
2017-05-25 05:52:49.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09500000000000501, -0.09500000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[913, 914, 928, 960, 1014, 1091, 1190, 1307, 1...",NaN,NaN,1
2017-05-25 05:52:49.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.140000000000007, -0.11...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2300, 2259, 2218, 2174, 2122, 2093, 2077, 204...",NaN,NaN,1
2017-05-25 05:52:49.360000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,18.0,98.8,1
2017-05-25 05:52:49.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.159999999999989, 0.17999999999999203, 0.199...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1679, 1657, 1635, 1613, 1590, 1566, 1542, 152...",NaN,NaN,1
2017-05-25 05:52:49.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1194, 1196, 1204, 1224, 1259, 1313, 1385, 147...",NaN,NaN,1
2017-05-25 05:52:50.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.075000000000009, -0.075000000000009, -0.08...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2462, 2438, 2410, 2376, 2337, 2292, 2248, 220...",NaN,NaN,1
2017-05-25 05:52:50.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.06999999999999301, 0.08499999999999301, 0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1715, 1692, 1669, 1646, 1623, 1601, 1579, 155...",NaN,NaN,1
2017-05-25 05:52:50.384000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,18.0,98.8,1
2017-05-25 05:52:50.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.120000000000004, -0.12...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1214, 1203, 1194, 1190, 1195, 1211, 1242, 129...",NaN,NaN,1
2017-05-25 05:52:50.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10500000000000301, -0.10500000000000301, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2491, 2480, 2467, 2450, 2427, 2397, 2360, 231...",NaN,NaN,1
2017-05-25 05:52:51.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.030000000000008003, -0.025000000000005, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1746, 1722, 1702, 1684, 1663, 1641, 1619, 159...",NaN,NaN,1
2017-05-25 05:52:51.344000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.15500000000000802, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1234, 1227, 1220, 1213, 1205, 1159, 1097, 107...",NaN,NaN,1
2017-05-25 05:52:51.408000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,18.0,98.8,1
2017-05-25 05:52:51.600000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.120000000000004, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2862, 2849, 2835, 2820, 2804, 2784, 2761, 273...",NaN,NaN,1
2017-05-25 05:52:51.856000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.075000000000009, -0.075000000000009, -0.07...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1968, 1946, 1920, 1890, 1858, 1823, 1793, 176...",NaN,NaN,1
2017-05-25 05:52:52.112000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.160000000000003, -0.160000000000003, -0.16...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1156, 1151, 1144, 1137, 1128, 1118, 1107, 109...",NaN,NaN,1
2017-05-25 05:52:52.368000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.045000000000008006,...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2743, 2742, 2736, 2726, 2714, 2700, 2686, 267...",NaN,NaN,1
2017-05-25 05:52:52.432000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,18.0,98.8,1
2017-05-25 05:52:52.624000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.130000000000009, -0.130000000000009, -0.12...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2014, 2009, 2001, 1987, 1968, 1945, 1918, 188...",NaN,NaN,1
2017-05-25 05:52:52.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.165000000000006, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1274, 1256, 1241, 1233, 1230, 1225, 1220, 121...",NaN,NaN,1
2017-05-25 05:52:53.136000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.12500000000000702, -0.12500000000000702, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2500, 2602, 2689, 2761, 2819, 2864, 2896, 291...",NaN,NaN,1
2017-05-25 05:52:53.392000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.11500000000000901, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2181, 2165, 2155, 2148, 2144, 2161, 2188, 219...",NaN,NaN,1
2017-05-25 05:52:53.456000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,70.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,18.0,98.8,1
2017-05-25 05:52:53.648000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1544, 1519, 1495, 1472, 1448, 1424, 1400, 138...",NaN,NaN,1
2017-05-25 05:52:53.904000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.19500000000000703, -0.19500000000000703, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1170, 1176, 1180, 1183, 1186, 1188, 1188, 118...",NaN,NaN,1
2017-05-25 05:52:54.160000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.14500000000001, -0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3289, 3305, 3313, 3313, 3307, 3294, 3278, 326...",NaN,NaN,1
2017-05-25 05:52:54.416000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11500000000000901, -0.12500000000000702, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2481, 2479, 2473, 2461, 2445, 2423, 2397, 236...",NaN,NaN,1
2017-05-25 05:52:54.480000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,72.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",None,18.0,98.9,1
2017-05-25 05:52:54.672000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.044999999999994, 0.059999999999995, 0.06999...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1544, 1520, 1498, 1482, 1471, 1458, 1445, 143...",NaN,NaN,1
2017-05-25 05:52:54.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15500000000000802, -0.15500000000000802, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1273, 1268, 1265, 1266, 1279, 1310, 1364, 144...",NaN,NaN,1

In [19]:
sliced_df.to_csv("sliced_dataframe.csv" ,  index = True)

In [20]:
sliced_df = pd.read_csv("sliced_dataframe.csv")

In [21]:
sliced_df

,timestamp,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,qos
0,2017-05-25 05:44:35.216000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.065000000000004, -0.08000000000000501, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2996, 2986, 2966, 2937, 2901, 2862, 2821, 277...",NaN,NaN,1
1,2017-05-25 05:44:35.472000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.025000000000005, -0.020000000000010003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1775, 1779, 1780, 1777, 1769, 1757, 1741, 172...",NaN,NaN,1
2,2017-05-25 05:44:35.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1218, 1210, 1201, 1196, 1193, 1186, 1177, 116...",NaN,NaN,1
3,2017-05-25 05:44:35.792000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1
4,2017-05-25 05:44:35.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.034999999999989005, 0.009999999999990001, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2972, 2980, 2978, 2967, 2948, 2931, 2913, 288...",NaN,NaN,1
5,2017-05-25 05:44:36.240000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1713, 1713, 1714, 1713, 1710, 1704, 1695, 168...",NaN,NaN,1
6,2017-05-25 05:44:36.496000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1163, 1150, 1138, 1127, 1116, 1105, 1094, 108...",NaN,NaN,1
7,2017-05-25 05:44:36.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.035000000000003, -0.045000000000008006, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2922, 2955, 2981, 2998, 3005, 3002, 2990, 297...",NaN,NaN,1
8,2017-05-25 05:44:36.816000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1
9,2017-05-25 05:44:37.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.15000000000000502, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1728, 1724, 1723, 1723, 1722, 1721, 1719, 171...",NaN,NaN,1
10,2017-05-25 05:44:37.264000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.160000000000003, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1179, 1167, 1156, 1146, 1136, 1127, 1119, 111...",NaN,NaN,1
11,2017-05-25 05:44:37.520000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.135000000000005, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2352, 2495, 2622, 2731, 2810, 2868, 2922, 296...",NaN,NaN,1
12,2017-05-25 05:44:37.776000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.19500000000000703, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1850, 1812, 1783, 1762, 1749, 1741, 1738, 173...",NaN,NaN,1
13,2017-05-25 05:44:37.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1
14,2017-05-25 05:44:38.032000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.23999999999999402, 0.20999999999999303, 0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1298, 1274, 1256, 1242, 1225, 1217, 1213, 120...",NaN,NaN,1
15,2017-05-25 05:44:38.288000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.14500000000001, -0.1400...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1261, 1387, 1537, 1704, 1881, 2059, 2230, 237...",NaN,NaN,1
16,2017-05-25 05:44:38.544000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.035000000000003, 0.22999999999998902, 0.69...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2322, 2253, 2177, 2101, 2030, 1966, 1911, 186...",NaN,NaN,1
17,2017-05-25 05:44:38.800000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.20999999999999303, 0.22999999999998902, 0.2...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1526, 1495, 1465, 1436, 1408, 1381, 1360, 134...",NaN,NaN,1
18,2017-05-25 05:44:38.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.4,1
19,2017-05-25 05:44:39.056000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1074, 1078, 1096, 1136, 1204, 1303, 1433, 158...",NaN,NaN,1
20,2017-05-25 05:44:39.312000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2606, 2541, 2470, 2393, 2320, 2249, 2170, 209...",NaN,NaN,1
21,2017-05-25 05:44:39.568000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.049999999999990004, 0.06499999999999001, 0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1625, 1598, 1569, 1539, 1508, 1477, 1445, 141...",NaN,NaN,1
22,2017-05-25 05:44:39.824000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.140000000000007, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1064, 1049, 1039, 1032, 1024, 1024, 1038, 107...",NaN,NaN,1
23,2017-05-25 05:44:39.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.4,1
24,2017-05-25 05:44:40.080000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09000000000001, -0.09000000000001, -0.0900...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2938, 2896, 2851, 2803, 2750, 2689, 2620, 254...",NaN,NaN,1
25,2017-05-25 05:44:40.336000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.040000000000006, -0.030000000000008003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1712, 1701, 1688, 1671, 1650, 1627, 1602, 157...",NaN,NaN,1
26,2017-05-25 05:44:40.592000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.140000000000007, -0.140...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1112, 1105, 1097, 1088, 1077, 1064, 1055, 104...",NaN,NaN,1
27,2017-05-25 05:44:40.848000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.08000000000000501, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3034, 3017, 2994, 2964, 2928, 2888, 2844, 279...",NaN,NaN,1
28,2017-05-25 05:44:40.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,76.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.3,1
29,2017-05-25 05:44:41.104000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1754, 1752, 1747, 1738, 1725, 1712, 1698, 168...",NaN,NaN,1
...,...,...,...,...,...,...,...,...,...
2411,2017-05-25 05:52:49.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09500000000000501, -0.09500000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[913, 914, 928, 960, 1014, 1091, 1190, 1307, 1...",NaN,NaN,1
2412,2017-05-25 05:52:49.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.140000000000007, -0.11...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2300, 2259, 2218, 2174, 2122, 2093, 2077, 204...",NaN,NaN,1
2413,2017-05-25 05:52:49.360000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1
2414,2017-05-25 05:52:49.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.159999999999989, 0.17999999999999203, 0.199...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1679, 1657, 1635, 1613, 1590, 1566, 1542, 152...",NaN,NaN,1
2415,2017-05-25 05:52:49.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1194, 1196, 1204, 1224, 1259, 1313, 1385, 147...",NaN,NaN,1
2416,2017-05-25 05:52:50.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.075000000000009, -0.075000000000009, -0.08...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2462, 2438, 2410, 2376, 2337, 2292, 2248, 220...",NaN,NaN,1
2417,2017-05-25 05:52:50.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.06999999999999301, 0.08499999999999301, 0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1715, 1692, 1669, 1646, 1623, 1601, 1579, 155...",NaN,NaN,1
2418,2017-05-25 05:52:50.384000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1
2419,2017-05-25 05:52:50.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.120000000000004, -0.12...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1214, 1203, 1194, 1190, 1195, 1211, 1242, 129...",NaN,NaN,1
2420,2017-05-25 05:52:50.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10500000000000301, -0.10500000000000301, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2491, 2480, 2467, 2450, 2427, 2397, 2360, 231...",NaN,NaN,1
2421,2017-05-25 05:52:51.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.030000000000008003, -0.025000000000005, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1746, 1722, 1702, 1684, 1663, 1641, 1619, 159...",NaN,NaN,1
2422,2017-05-25 05:52:51.344000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.15500000000000802, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1234, 1227, 1220, 1213, 1205, 1159, 1097, 107...",NaN,NaN,1
2423,2017-05-25 05:52:51.408000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1
2424,2017-05-25 05:52:51.600000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.120000000000004, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2862, 2849, 2835, 2820, 2804, 2784, 2761, 273...",NaN,NaN,1
2425,2017-05-25 05:52:51.856000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.075000000000009, -0.075000000000009, -0.07...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1968, 1946, 1920, 1890, 1858, 1823, 1793, 176...",NaN,NaN,1
2426,2017-05-25 05:52:52.112000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.160000000000003, -0.160000000000003, -0.16...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1156, 1151, 1144, 1137, 1128, 1118, 1107, 109...",NaN,NaN,1
2427,2017-05-25 05:52:52.368000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.045000000000008006,...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2743, 2742, 2736, 2726, 2714, 2700, 2686, 267...",NaN,NaN,1
2428,2017-05-25 05:52:52.432000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1
2429,2017-05-25 05:52:52.624000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.130000000000009, -0.130000000000009, -0.12...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2014, 2009, 2001, 1987, 1968, 1945, 1918, 188...",NaN,NaN,1
2430,2017-05-25 05:52:52.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.165000000000006, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1274, 1256, 1241, 1233, 1230, 1225, 1220, 121...",NaN,NaN,1
2431,2017-05-25 05:52:53.136000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.12500000000000702, -0.12500000000000702, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2500, 2602, 2689, 2761, 2819, 2864, 2896, 291...",NaN,NaN,1
2432,2017-05-25 05:52:53.392000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.11500000000000901, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2181, 2165, 2155, 2148, 2144, 2161, 2188, 219...",NaN,NaN,1
2433,2017-05-25 05:52:53.456000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,70.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1
2434,2017-05-25 05:52:53.648000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1544, 1519, 1495, 1472, 1448, 1424, 1400, 138...",NaN,NaN,1
2435,2017-05-25 05:52:53.904000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.19500000000000703, -0.19500000000000703, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1170, 1176, 1180, 1183, 1186, 1188, 1188, 118...",NaN,NaN,1
2436,2017-05-25 05:52:54.160000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.14500000000001, -0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3289, 3305, 3313, 3313, 3307, 3294, 3278, 326...",NaN,NaN,1
2437,2017-05-25 05:52:54.416000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11500000000000901, -0.12500000000000702, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2481, 2479, 2473, 2461, 2445, 2423, 2397, 236...",NaN,NaN,1
2438,2017-05-25 05:52:54.480000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,72.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.9,1
2439,2017-05-25 05:52:54.672000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.044999999999994, 0.059999999999995, 0.06999...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1544, 1520, 1498, 1482, 1471, 1458, 1445, 143...",NaN,NaN,1
2440,2017-05-25 05:52:54.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15500000000000802, -0.15500000000000802, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1273, 1268, 1265, 1266, 1279, 1310, 1364, 144...",NaN,NaN,1

In [22]:
tot_cnt = len(sliced_df)
l = [0 for i in range(tot_cnt - 1)] # 0 indicates NO alarm
l.append(1)                         # 1 indicates Real alarm
df = pd.DataFrame(np.array(l), columns = ["Annotated ECG alarm"])

In [23]:
df

      Annotated ECG alarm
0                       0
1                       0
2                       0
3                       0
4                       0
5                       0
6                       0
7                       0
8                       0
9                       0
10                      0
11                      0
12                      0
13                      0
14                      0
15                      0
16                      0
17                      0
18                      0
19                      0
20                      0
21                      0
22                      0
23                      0
24                      0
25                      0
26                      0
27                      0
28                      0
29                      0
...                   ...
2411                    0
2412                    0
2413                    0
2414                    0
2415                    0
2416                    0
2417                    0
2418                    0
2419                    0
2420                    0
2421                    0
2422                    0
2423                    0
2424                    0
2425                    0
2426                    0
2427                    0
2428                    0
2429                    0
2430                    0
2431                    0
2432                    0
2433                    0
2434                    0
2435                    0
2436                    0
2437                    0
2438                    0
2439                    0
2440                    1

[2441 rows x 1 columns]

In [24]:
sliced_df = pd.concat([sliced_df, df], axis = 1)
sliced_df

,timestamp,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,qos,Annotated ECG alarm
0,2017-05-25 05:44:35.216000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.065000000000004, -0.08000000000000501, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2996, 2986, 2966, 2937, 2901, 2862, 2821, 277...",NaN,NaN,1,0
1,2017-05-25 05:44:35.472000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.025000000000005, -0.020000000000010003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1775, 1779, 1780, 1777, 1769, 1757, 1741, 172...",NaN,NaN,1,0
2,2017-05-25 05:44:35.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1218, 1210, 1201, 1196, 1193, 1186, 1177, 116...",NaN,NaN,1,0
3,2017-05-25 05:44:35.792000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1,0
4,2017-05-25 05:44:35.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.034999999999989005, 0.009999999999990001, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2972, 2980, 2978, 2967, 2948, 2931, 2913, 288...",NaN,NaN,1,0
5,2017-05-25 05:44:36.240000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1713, 1713, 1714, 1713, 1710, 1704, 1695, 168...",NaN,NaN,1,0
6,2017-05-25 05:44:36.496000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1163, 1150, 1138, 1127, 1116, 1105, 1094, 108...",NaN,NaN,1,0
7,2017-05-25 05:44:36.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.035000000000003, -0.045000000000008006, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2922, 2955, 2981, 2998, 3005, 3002, 2990, 297...",NaN,NaN,1,0
8,2017-05-25 05:44:36.816000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1,0
9,2017-05-25 05:44:37.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.15000000000000502, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1728, 1724, 1723, 1723, 1722, 1721, 1719, 171...",NaN,NaN,1,0
10,2017-05-25 05:44:37.264000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.160000000000003, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1179, 1167, 1156, 1146, 1136, 1127, 1119, 111...",NaN,NaN,1,0
11,2017-05-25 05:44:37.520000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.135000000000005, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2352, 2495, 2622, 2731, 2810, 2868, 2922, 296...",NaN,NaN,1,0
12,2017-05-25 05:44:37.776000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.19500000000000703, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1850, 1812, 1783, 1762, 1749, 1741, 1738, 173...",NaN,NaN,1,0
13,2017-05-25 05:44:37.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1,0
14,2017-05-25 05:44:38.032000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.23999999999999402, 0.20999999999999303, 0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1298, 1274, 1256, 1242, 1225, 1217, 1213, 120...",NaN,NaN,1,0
15,2017-05-25 05:44:38.288000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.14500000000001, -0.1400...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1261, 1387, 1537, 1704, 1881, 2059, 2230, 237...",NaN,NaN,1,0
16,2017-05-25 05:44:38.544000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.035000000000003, 0.22999999999998902, 0.69...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2322, 2253, 2177, 2101, 2030, 1966, 1911, 186...",NaN,NaN,1,0
17,2017-05-25 05:44:38.800000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.20999999999999303, 0.22999999999998902, 0.2...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1526, 1495, 1465, 1436, 1408, 1381, 1360, 134...",NaN,NaN,1,0
18,2017-05-25 05:44:38.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.4,1,0
19,2017-05-25 05:44:39.056000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1074, 1078, 1096, 1136, 1204, 1303, 1433, 158...",NaN,NaN,1,0
20,2017-05-25 05:44:39.312000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2606, 2541, 2470, 2393, 2320, 2249, 2170, 209...",NaN,NaN,1,0
21,2017-05-25 05:44:39.568000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.049999999999990004, 0.06499999999999001, 0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1625, 1598, 1569, 1539, 1508, 1477, 1445, 141...",NaN,NaN,1,0
22,2017-05-25 05:44:39.824000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.140000000000007, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1064, 1049, 1039, 1032, 1024, 1024, 1038, 107...",NaN,NaN,1,0
23,2017-05-25 05:44:39.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.4,1,0
24,2017-05-25 05:44:40.080000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09000000000001, -0.09000000000001, -0.0900...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2938, 2896, 2851, 2803, 2750, 2689, 2620, 254...",NaN,NaN,1,0
25,2017-05-25 05:44:40.336000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.040000000000006, -0.030000000000008003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1712, 1701, 1688, 1671, 1650, 1627, 1602, 157...",NaN,NaN,1,0
26,2017-05-25 05:44:40.592000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.140000000000007, -0.140...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1112, 1105, 1097, 1088, 1077, 1064, 1055, 104...",NaN,NaN,1,0
27,2017-05-25 05:44:40.848000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.08000000000000501, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3034, 3017, 2994, 2964, 2928, 2888, 2844, 279...",NaN,NaN,1,0
28,2017-05-25 05:44:40.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,76.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.3,1,0
29,2017-05-25 05:44:41.104000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1754, 1752, 1747, 1738, 1725, 1712, 1698, 168...",NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...
2411,2017-05-25 05:52:49.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09500000000000501, -0.09500000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[913, 914, 928, 960, 1014, 1091, 1190, 1307, 1...",NaN,NaN,1,0
2412,2017-05-25 05:52:49.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.140000000000007, -0.11...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2300, 2259, 2218, 2174, 2122, 2093, 2077, 204...",NaN,NaN,1,0
2413,2017-05-25 05:52:49.360000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1,0
2414,2017-05-25 05:52:49.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.159999999999989, 0.17999999999999203, 0.199...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1679, 1657, 1635, 1613, 1590, 1566, 1542, 152...",NaN,NaN,1,0
2415,2017-05-25 05:52:49.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1194, 1196, 1204, 1224, 1259, 1313, 1385, 147...",NaN,NaN,1,0
2416,2017-05-25 05:52:50.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.075000000000009, -0.075000000000009, -0.08...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2462, 2438, 2410, 2376, 2337, 2292, 2248, 220...",NaN,NaN,1,0
2417,2017-05-25 05:52:50.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.06999999999999301, 0.08499999999999301, 0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1715, 1692, 1669, 1646, 1623, 1601, 1579, 155...",NaN,NaN,1,0
2418,2017-05-25 05:52:50.384000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1,0
2419,2017-05-25 05:52:50.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.120000000000004, -0.12...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1214, 1203, 1194, 1190, 1195, 1211, 1242, 129...",NaN,NaN,1,0
2420,2017-05-25 05:52:50.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10500000000000301, -0.10500000000000301, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2491, 2480, 2467, 2450, 2427, 2397, 2360, 231...",NaN,NaN,1,0
2421,2017-05-25 05:52:51.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.030000000000008003, -0.025000000000005, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1746, 1722, 1702, 1684, 1663, 1641, 1619, 159...",NaN,NaN,1,0
2422,2017-05-25 05:52:51.344000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.15500000000000802, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1234, 1227, 1220, 1213, 1205, 1159, 1097, 107...",NaN,NaN,1,0
2423,2017-05-25 05:52:51.408000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1,0
2424,2017-05-25 05:52:51.600000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.120000000000004, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2862, 2849, 2835, 2820, 2804, 2784, 2761, 273...",NaN,NaN,1,0
2425,2017-05-25 05:52:51.856000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.075000000000009, -0.075000000000009, -0.07...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1968, 1946, 1920, 1890, 1858, 1823, 1793, 176...",NaN,NaN,1,0
2426,2017-05-25 05:52:52.112000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.160000000000003, -0.160000000000003, -0.16...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1156, 1151, 1144, 1137, 1128, 1118, 1107, 109...",NaN,NaN,1,0
2427,2017-05-25 05:52:52.368000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.045000000000008006,...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2743, 2742, 2736, 2726, 2714, 2700, 2686, 267...",NaN,NaN,1,0
2428,2017-05-25 05:52:52.432000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,68.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1,0
2429,2017-05-25 05:52:52.624000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.130000000000009, -0.130000000000009, -0.12...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2014, 2009, 2001, 1987, 1968, 1945, 1918, 188...",NaN,NaN,1,0
2430,2017-05-25 05:52:52.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.165000000000006, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1274, 1256, 1241, 1233, 1230, 1225, 1220, 121...",NaN,NaN,1,0
2431,2017-05-25 05:52:53.136000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.12500000000000702, -0.12500000000000702, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2500, 2602, 2689, 2761, 2819, 2864, 2896, 291...",NaN,NaN,1,0
2432,2017-05-25 05:52:53.392000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.11500000000000901, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2181, 2165, 2155, 2148, 2144, 2161, 2188, 219...",NaN,NaN,1,0
2433,2017-05-25 05:52:53.456000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,70.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.8,1,0
2434,2017-05-25 05:52:53.648000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1544, 1519, 1495, 1472, 1448, 1424, 1400, 138...",NaN,NaN,1,0
2435,2017-05-25 05:52:53.904000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.19500000000000703, -0.19500000000000703, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1170, 1176, 1180, 1183, 1186, 1188, 1188, 118...",NaN,NaN,1,0
2436,2017-05-25 05:52:54.160000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.14500000000001, -0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3289, 3305, 3313, 3313, 3307, 3294, 3278, 326...",NaN,NaN,1,0
2437,2017-05-25 05:52:54.416000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11500000000000901, -0.12500000000000702, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2481, 2479, 2473, 2461, 2445, 2423, 2397, 236...",NaN,NaN,1,0
2438,2017-05-25 05:52:54.480000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,72.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,18.0,98.9,1,0
2439,2017-05-25 05:52:54.672000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.044999999999994, 0.059999999999995, 0.06999...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1544, 1520, 1498, 1482, 1471, 1458, 1445, 143...",NaN,NaN,1,0
2440,2017-05-25 05:52:54.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15500000000000802, -0.15500000000000802, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1273, 1268, 1265, 1266, 1279, 1310, 1364, 144...",NaN,NaN,1,1

In [25]:
for i in range(len(alarms)):
    alarm = alarms[i]
    isolated_df = cleaned_df[alarm - pd.Timedelta("500 seconds"):alarm]
    isolated_df.to_csv("sliced_dataframe.csv" ,  index = True)
    isolated_df = pd.read_csv("sliced_dataframe.csv")
    
    tot_cnt = len(isolated_df)
    # Create a new dataframe indicating "real" alarms
    l = [0 for i in range(tot_cnt - 1)] # 0 indicates NO alarm
    l.append(1)                         # 1 indicates Real alarm
    df = pd.DataFrame(np.array(l), columns = ["Annotated ECG alarm"])
    isolated_df = pd.concat([isolated_df, df], axis = 1)
    
    if (tot_cnt == 0):
        continue
    good_df = isolated_df.loc[isolated_df['qos'] == 1]
    good_cnt = len(good_df)
    good_ratio = good_cnt/tot_cnt
    if i == 0:
        sliced_df = isolated_df.copy()
    elif good_ratio > 0.8:
        sliced_df = pd.concat([sliced_df, isolated_df], axis = 0)
    print("Alarm NO. {0:2d} Good data ratio of this alarm window is: {1:4f}".format(i,good_ratio))

Alarm NO.  0 Good data ratio of this alarm window is: 0.999590
Alarm NO.  1 Good data ratio of this alarm window is: 0.999590
Alarm NO.  2 Good data ratio of this alarm window is: 0.999590
Alarm NO.  3 Good data ratio of this alarm window is: 0.999590
Alarm NO.  4 Good data ratio of this alarm window is: 0.999590
Alarm NO.  5 Good data ratio of this alarm window is: 0.999590
Alarm NO.  6 Good data ratio of this alarm window is: 0.994265
Alarm NO.  7 Good data ratio of this alarm window is: 0.131222
Alarm NO.  8 Good data ratio of this alarm window is: 0.535700
Alarm NO.  9 Good data ratio of this alarm window is: 0.536924
Alarm NO. 10 Good data ratio of this alarm window is: 0.658871
Alarm NO. 11 Good data ratio of this alarm window is: 0.000000
Alarm NO. 13 Good data ratio of this alarm window is: 0.000000
Alarm NO. 14 Good data ratio of this alarm window is: 0.000000
Alarm NO. 15 Good data ratio of this alarm window is: 0.000000
Alarm NO. 16 Good data ratio of this alarm window is: 0.000000
Alarm NO. 17 Good data ratio of this alarm window is: 0.000000
Alarm NO. 18 Good data ratio of this alarm window is: 0.000000
Alarm NO. 19 Good data ratio of this alarm window is: 0.000000
Alarm NO. 20 Good data ratio of this alarm window is: 0.000000
Alarm NO. 21 Good data ratio of this alarm window is: 0.000000
Alarm NO. 23 Good data ratio of this alarm window is: 0.268068
Alarm NO. 24 Good data ratio of this alarm window is: 0.000000

In [26]:
sliced_df

,timestamp,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,qos,Annotated ECG alarm
0,2017-05-25 05:44:35.216000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.065000000000004, -0.08000000000000501, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2996, 2986, 2966, 2937, 2901, 2862, 2821, 277...",NaN,NaN,1,0
1,2017-05-25 05:44:35.472000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.025000000000005, -0.020000000000010003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1775, 1779, 1780, 1777, 1769, 1757, 1741, 172...",NaN,NaN,1,0
2,2017-05-25 05:44:35.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1218, 1210, 1201, 1196, 1193, 1186, 1177, 116...",NaN,NaN,1,0
3,2017-05-25 05:44:35.792000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1,0
4,2017-05-25 05:44:35.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.034999999999989005, 0.009999999999990001, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2972, 2980, 2978, 2967, 2948, 2931, 2913, 288...",NaN,NaN,1,0
5,2017-05-25 05:44:36.240000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1713, 1713, 1714, 1713, 1710, 1704, 1695, 168...",NaN,NaN,1,0
6,2017-05-25 05:44:36.496000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1163, 1150, 1138, 1127, 1116, 1105, 1094, 108...",NaN,NaN,1,0
7,2017-05-25 05:44:36.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.035000000000003, -0.045000000000008006, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2922, 2955, 2981, 2998, 3005, 3002, 2990, 297...",NaN,NaN,1,0
8,2017-05-25 05:44:36.816000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1,0
9,2017-05-25 05:44:37.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.15000000000000502, -0.15000000000000502, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1728, 1724, 1723, 1723, 1722, 1721, 1719, 171...",NaN,NaN,1,0
10,2017-05-25 05:44:37.264000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.160000000000003, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1179, 1167, 1156, 1146, 1136, 1127, 1119, 111...",NaN,NaN,1,0
11,2017-05-25 05:44:37.520000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.135000000000005, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2352, 2495, 2622, 2731, 2810, 2868, 2922, 296...",NaN,NaN,1,0
12,2017-05-25 05:44:37.776000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.19500000000000703, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1850, 1812, 1783, 1762, 1749, 1741, 1738, 173...",NaN,NaN,1,0
13,2017-05-25 05:44:37.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.5,1,0
14,2017-05-25 05:44:38.032000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.23999999999999402, 0.20999999999999303, 0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1298, 1274, 1256, 1242, 1225, 1217, 1213, 120...",NaN,NaN,1,0
15,2017-05-25 05:44:38.288000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.14500000000001, -0.1400...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1261, 1387, 1537, 1704, 1881, 2059, 2230, 237...",NaN,NaN,1,0
16,2017-05-25 05:44:38.544000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.035000000000003, 0.22999999999998902, 0.69...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2322, 2253, 2177, 2101, 2030, 1966, 1911, 186...",NaN,NaN,1,0
17,2017-05-25 05:44:38.800000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.20999999999999303, 0.22999999999998902, 0.2...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1526, 1495, 1465, 1436, 1408, 1381, 1360, 134...",NaN,NaN,1,0
18,2017-05-25 05:44:38.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.4,1,0
19,2017-05-25 05:44:39.056000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1074, 1078, 1096, 1136, 1204, 1303, 1433, 158...",NaN,NaN,1,0
20,2017-05-25 05:44:39.312000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2606, 2541, 2470, 2393, 2320, 2249, 2170, 209...",NaN,NaN,1,0
21,2017-05-25 05:44:39.568000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.049999999999990004, 0.06499999999999001, 0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1625, 1598, 1569, 1539, 1508, 1477, 1445, 141...",NaN,NaN,1,0
22,2017-05-25 05:44:39.824000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.140000000000007, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1064, 1049, 1039, 1032, 1024, 1024, 1038, 107...",NaN,NaN,1,0
23,2017-05-25 05:44:39.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.4,1,0
24,2017-05-25 05:44:40.080000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09000000000001, -0.09000000000001, -0.0900...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2938, 2896, 2851, 2803, 2750, 2689, 2620, 254...",NaN,NaN,1,0
25,2017-05-25 05:44:40.336000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.040000000000006, -0.030000000000008003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1712, 1701, 1688, 1671, 1650, 1627, 1602, 157...",NaN,NaN,1,0
26,2017-05-25 05:44:40.592000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.140000000000007, -0.140...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1112, 1105, 1097, 1088, 1077, 1064, 1055, 104...",NaN,NaN,1,0
27,2017-05-25 05:44:40.848000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.060000000000009004, -0.08000000000000501, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3034, 3017, 2994, 2964, 2928, 2888, 2844, 279...",NaN,NaN,1,0
28,2017-05-25 05:44:40.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,76.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,16.0,98.3,1,0
29,2017-05-25 05:44:41.104000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1754, 1752, 1747, 1738, 1725, 1712, 1698, 168...",NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...
2411,2017-05-25 06:09:23.344000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.034999999999989005, 0.024999999999991, -7.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2453, 2430, 2403, 2371, 2334, 2292, 2251, 221...",NaN,NaN,1,0
2412,2017-05-25 06:09:23.600000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.070000000000007, -0.070000000000007, -0.06...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1796, 1778, 1759, 1738, 1717, 1695, 1672, 164...",NaN,NaN,1,0
2413,2017-05-25 06:09:23.664000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,74.0,"{'mean': 68, 'systolic': 118, 'diastolic': 55}",NaN,19.0,99.3,1,0
2414,2017-05-25 06:09:23.856000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.14500000000001, -0.15000000000000502, -0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1336, 1328, 1319, 1310, 1304, 1300, 1293, 128...",NaN,NaN,1,0
2415,2017-05-25 06:09:24.112000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.070000000000007, -0.065000000000004, -0.07...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2499, 2509, 2618, 2772, 2842, 2867, 2868, 285...",NaN,NaN,1,0
2416,2017-05-25 06:09:24.368000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.18000000000000602, -0.165000000000006, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2063, 2057, 2050, 2042, 2030, 2015, 1997, 197...",NaN,NaN,1,0
2417,2017-05-25 06:09:24.624000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.11499999999999401, 0.074999999999995, 0.029...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1392, 1378, 1364, 1350, 1336, 1323, 1311, 130...",NaN,NaN,1,0
2418,2017-05-25 06:09:24.688000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,74.0,"{'mean': 68, 'systolic': 118, 'diastolic': 55}",NaN,19.0,99.2,1,0
2419,2017-05-25 06:09:24.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10500000000000301, -0.10500000000000301, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2234, 2350, 2449, 2549, 2642, 2726, 2797, 285...",NaN,NaN,1,0
2420,2017-05-25 06:09:25.136000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11500000000000901, -0.11500000000000901, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2269, 2222, 2182, 2150, 2125, 2107, 2094, 208...",NaN,NaN,1,0
2421,2017-05-25 06:09:25.392000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.015000000000007, -0.005000000000009001, 0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1581, 1560, 1539, 1518, 1497, 1476, 1456, 143...",NaN,NaN,1,0
2422,2017-05-25 06:09:25.648000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.165000000000006, -0.160000000000003, -0.16...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1210, 1202, 1203, 1216, 1247, 1291, 1351, 143...",NaN,NaN,1,0
2423,2017-05-25 06:09:25.712000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,74.0,"{'mean': 68, 'systolic': 118, 'diastolic': 55}",NaN,19.0,99.2,1,0
2424,2017-05-25 06:09:25.904000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.004999999999995001, 0.014999999999993002, 0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2954, 2928, 2898, 2861, 2817, 2766, 2707, 264...",NaN,NaN,1,0
2425,2017-05-25 06:09:26.160000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11500000000000901, -0.11000000000000601, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2011, 1984, 1936, 1881, 1841, 1803, 1765, 172...",NaN,NaN,1,0
2426,2017-05-25 06:09:26.416000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.170000000000008, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1194, 1186, 1177, 1168, 1159, 1149, 1140, 113...",NaN,NaN,1,0
2427,2017-05-25 06:09:26.672000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09500000000000501, -0.09500000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3087, 3139, 3174, 3205, 3228, 3242, 3248, 324...",NaN,NaN,1,0
2428,2017-05-25 06:09:26.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,74.0,"{'mean': 68, 'systolic': 118, 'diastolic': 55}",NaN,19.0,99.2,1,0
2429,2017-05-25 06:09:26.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.165000000000006, -0.19500000000000703, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2271, 2272, 2272, 2271, 2268, 2260, 2248, 223...",NaN,NaN,1,0
2430,2017-05-25 06:09:27.184000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.25999999999999, 0.21499999999999603, 0.1749...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1476, 1465, 1451, 1436, 1421, 1407, 1393, 138...",NaN,NaN,1,0
2431,2017-05-25 06:09:27.440000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.09000000000001, -0.09000000000001, -0.0900...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2103, 2288, 2473, 2653, 2824, 2962, 3077, 319...",NaN,NaN,1,0
2432,2017-05-25 06:09:27.696000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2771, 2692, 2618, 2552, 2495, 2448, 2409, 237...",NaN,NaN,1,0
2433,2017-05-25 06:09:27.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,73.0,"{'mean': 68, 'systolic': 118, 'diastolic': 55}",NaN,19.0,99.1,1,0
2434,2017-05-25 06:09:27.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.009999999999990001, 0.019999999999996, 0.03...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1720, 1680, 1642, 1612, 1587, 1560, 1532, 150...",NaN,NaN,1,0
2435,2017-05-25 06:09:28.208000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.140000000000007, -0.140000000000007, -0.14...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1170, 1160, 1136, 1112, 1116, 1146, 1202, 128...",NaN,NaN,1,0
2436,2017-05-25 06:09:28.464000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[0.014999999999993002, 0.024999999999991, 0.01...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2945, 2905, 2862, 2817, 2765, 2706, 2641, 257...",NaN,NaN,1,0
2437,2017-05-25 06:09:28.720000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.11000000000000601, -0.10500000000000301, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1789, 1762, 1732, 1700, 1668, 1636, 1604, 157...",NaN,NaN,1,0
2438,2017-05-25 06:09:28.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}",NaN,73.0,"{'mean': 68, 'systolic': 118, 'diastolic': 55}",NaN,19.0,99.1,1,0
2439,2017-05-25 06:09:28.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.170000000000008, -0.170000000000008, -0.16...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1084, 1082, 1078, 1073, 1067, 1060, 1052, 104...",NaN,NaN,1,0
2440,2017-05-25 06:09:29.232000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2878, 2913, 2935, 2946, 2946, 2938, 2921, 289...",NaN,NaN,1,1

In [27]:
sliced_df[["diastolic_bp","mean_bp","systolic_bp"]] = sliced_df["Non-invasive Blood Pressure"].apply(lambda x : dict(eval(x))).apply(pd.Series )
sliced_df = sliced_df.drop("Non-invasive Blood Pressure", axis=1)

In [28]:
sliced_df = sliced_df.drop(["Respiration Rate"], axis=1)
sliced_df[["Respiration Rate","etCO2"]] = sliced_df["Airway"].apply(lambda x : dict(eval(x))).apply(pd.Series )
sliced_df = sliced_df.drop(["Airway"], axis=1)