## Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
%matplotlib inline

## Create functions for assigning timestamps to signals

Data arrives in packets of 64 (ecg) or 32 (pleth) with a single timestamp. Therefore, each array needs to manually be assigned individual timestamps.

In [2]:
def expand_pleth_times(timestamp):
    x = pd.date_range(timestamp, periods=32,freq='8L',closed="left")
    return x

def expand_ecg_times(timestamp):
    x = pd.date_range(timestamp, periods=64,freq='4L',closed="left")
    return x

## Load and Clean Signals

* Load physio data
* Cleaning:
    * Timestamps/timezones -- physio data CSVs are time local (EST) but alamrs come with UTC offset.
        * Bokeh visualizer and pandas treat times as UTC, so must explicitly declare TZ intent.
    * Merge duplicate timestamp entries into 1 row

In [3]:
fname = '../../original_data/5-25-5-26'
physio_df = pd.read_json(fname, lines=True)

physio_df.set_index("timestamp",inplace=True)
physio_df.tz_localize('Etc/GMT+4',copy=False)
physio_df[['Heart Rate','Respiration Rate','SpO2','qos']] = physio_df[['Heart Rate','Respiration Rate','SpO2','qos']].apply(pd.to_numeric,errors='coerce')

In [4]:
physio_df

,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,alarms,qos
timestamp,,,,,,,,,
2017-05-24 23:56:16.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,NaN,None,1
2017-05-24 23:56:17.016000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,NaN,None,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,NaN,None,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,96.7,None,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,1
2017-05-24 23:56:18.712000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:17.272000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,NaN,None,1
2017-05-24 23:56:17.528000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,NaN,None,1
2017-05-24 23:56:17.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,NaN,None,1
2017-05-24 23:56:18.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,NaN,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,NaN,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,96.5,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:18.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,NaN,None,1
2017-05-24 23:56:18.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,NaN,None,1
2017-05-24 23:56:18.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,NaN,None,1
2017-05-24 23:56:19.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,NaN,None,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,NaN,None,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,96.3,None,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,1
2017-05-24 23:56:20.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:19.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,NaN,None,1
2017-05-24 23:56:19.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,NaN,None,1
2017-05-24 23:56:19.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,NaN,None,1
2017-05-24 23:56:20.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,NaN,None,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,NaN,None,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,96.0,None,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,1
2017-05-24 23:56:21.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
...,...,...,...,...,...,...,...,...,...
2017-05-26 23:56:06.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:06.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:05.584000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.096000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.352000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:07.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:06.608000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.120000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.376000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:09.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:07.632000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.144000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.400000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:08.656000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:09.168000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:09.424000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0

In [5]:
'''
Collapse multiple entries for a single timestamp to one row.

Example, this:

        value_1 value_2 value_3
time_1    1        1      NaN
time_1    NaN     NaN      1

Becomes:
        value_1 value_2 value_3
time_1     1       1       1

'''
merged_df = physio_df.groupby("timestamp").first()
merged_df

,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,alarms,qos
timestamp,,,,,,,,,
2017-05-24 23:56:16.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,NaN,None,1
2017-05-24 23:56:17.016000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,NaN,None,1
2017-05-24 23:56:17.272000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,NaN,None,1
2017-05-24 23:56:17.528000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,NaN,None,1
2017-05-24 23:56:17.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,NaN,None,1
2017-05-24 23:56:18.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,NaN,None,1
2017-05-24 23:56:18.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,NaN,None,1
2017-05-24 23:56:18.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,NaN,None,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.7,None,1
2017-05-24 23:56:18.712000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:18.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,NaN,None,1
2017-05-24 23:56:19.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,NaN,None,1
2017-05-24 23:56:19.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,NaN,None,1
2017-05-24 23:56:19.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,NaN,None,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.5,None,1
2017-05-24 23:56:19.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,NaN,None,1
2017-05-24 23:56:20.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,NaN,None,1
2017-05-24 23:56:20.344000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2408, 2338, 2260, 2176, 2087, 1997, 1909, 183...",NaN,NaN,None,1
2017-05-24 23:56:20.600000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1113, 1098, 1076, 1050, 1021, 988, 955, 925, ...",NaN,NaN,None,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.3,None,1
2017-05-24 23:56:20.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:20.856000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2574, 2553, 2526, 2492, 2451, 2408, 2361, 230...",NaN,NaN,None,1
2017-05-24 23:56:21.112000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1279, 1263, 1246, 1227, 1243, 1276, 1281, 127...",NaN,NaN,None,1
2017-05-24 23:56:21.368000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2749, 2771, 2784, 2789, 2785, 2775, 2761, 274...",NaN,NaN,None,1
2017-05-24 23:56:21.624000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1581, 1564, 1547, 1529, 1511, 1492, 1472, 145...",NaN,NaN,None,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.0,None,1
2017-05-24 23:56:21.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,"{'Alarm_T_0': {'source': 'NOM_RESP', 'state': ...",1
2017-05-24 23:56:21.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2535, 2591, 2629, 2655, 2677, 2693, 2702, 270...",NaN,NaN,None,1
2017-05-24 23:56:22.136000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1609, 1588, 1570, 1552, 1535, 1518, 1501, 148...",NaN,NaN,None,1
2017-05-24 23:56:22.392000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2149, 2230, 2307, 2374, 2431, 2477, 251...",NaN,NaN,None,1
...,...,...,...,...,...,...,...,...,...
2017-05-26 23:56:04.304000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:04.560000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:04.816000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:04.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:04.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:05.072000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.328000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.584000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:05.904000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:06.096000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.352000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.608000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:06.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:07.120000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.376000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.632000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:07.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:08.144000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.400000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.656000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0
2017-05-26 23:56:09.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,{'Alarm_T_2': {'source': 'NOM_PULS_OXIM_SAT_O2...,0
2017-05-26 23:56:09.168000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:09.424000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,None,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,None,0

Drop machine generated alarms, since we are going to use the manually annotated alarms.

In [6]:
cleaned_df = merged_df.drop(['alarms'],axis = 1)
cleaned_df

,Airway,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,Respiration Rate,SpO2,qos
timestamp,,,,,,,,
2017-05-24 23:56:16.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,NaN,1
2017-05-24 23:56:17.016000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,NaN,1
2017-05-24 23:56:17.272000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,NaN,1
2017-05-24 23:56:17.528000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,NaN,1
2017-05-24 23:56:17.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,NaN,1
2017-05-24 23:56:18.040000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,NaN,1
2017-05-24 23:56:18.296000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,NaN,1
2017-05-24 23:56:18.552000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,NaN,1
2017-05-24 23:56:18.680000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.7,1
2017-05-24 23:56:18.712000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,1
2017-05-24 23:56:18.808000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,NaN,1
2017-05-24 23:56:19.064000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,NaN,1
2017-05-24 23:56:19.320000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,NaN,1
2017-05-24 23:56:19.576000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,NaN,1
2017-05-24 23:56:19.736000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.5,1
2017-05-24 23:56:19.832000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,NaN,1
2017-05-24 23:56:20.088000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,NaN,1
2017-05-24 23:56:20.344000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2408, 2338, 2260, 2176, 2087, 1997, 1909, 183...",NaN,NaN,1
2017-05-24 23:56:20.600000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1113, 1098, 1076, 1050, 1021, 988, 955, 925, ...",NaN,NaN,1
2017-05-24 23:56:20.728000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.3,1
2017-05-24 23:56:20.760000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,1
2017-05-24 23:56:20.856000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2574, 2553, 2526, 2492, 2451, 2408, 2361, 230...",NaN,NaN,1
2017-05-24 23:56:21.112000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1279, 1263, 1246, 1227, 1243, 1276, 1281, 127...",NaN,NaN,1
2017-05-24 23:56:21.368000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2749, 2771, 2784, 2789, 2785, 2775, 2761, 274...",NaN,NaN,1
2017-05-24 23:56:21.624000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1581, 1564, 1547, 1529, 1511, 1492, 1472, 145...",NaN,NaN,1
2017-05-24 23:56:21.752000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",None,NaN,96.0,1
2017-05-24 23:56:21.784000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,1
2017-05-24 23:56:21.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2535, 2591, 2629, 2655, 2677, 2693, 2702, 270...",NaN,NaN,1
2017-05-24 23:56:22.136000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1609, 1588, 1570, 1552, 1535, 1518, 1501, 148...",NaN,NaN,1
2017-05-24 23:56:22.392000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2149, 2230, 2307, 2374, 2431, 2477, 251...",NaN,NaN,1
...,...,...,...,...,...,...,...,...
2017-05-26 23:56:04.304000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:04.560000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:04.816000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:04.880000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:04.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,0
2017-05-26 23:56:05.072000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:05.328000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:05.584000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:05.840000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:05.904000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:06.096000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:06.352000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:06.608000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:06.864000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:06.928000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:07.120000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:07.376000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:07.632000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:07.888000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:07.952000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:07.984000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,0
2017-05-26 23:56:08.144000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:08.400000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:08.656000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:08.912000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:08.976000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0
2017-05-26 23:56:09.008000-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",None,NaN,NaN,0
2017-05-26 23:56:09.168000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:09.424000-04:00,"{'Respiration Rate': None, 'etCO2': None}","[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,NaN,0
2017-05-26 23:56:10-04:00,"{'Respiration Rate': None, 'etCO2': None}",None,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",None,NaN,NaN,0

Numerics values like airway values (including Respiration rate),etc. can be ignored for current analysis.

In [7]:
cleaned_df = cleaned_df.drop(["Respiration Rate"], axis=1)
cleaned_df = cleaned_df.drop(["Airway"], axis=1)

In [8]:
file_name = '../../clean_data/Model_Sherry/5-25-5-26_clean_del_alarm.csv'
cleaned_df.to_csv(file_name, encoding='utf-8', index=True)
clean_df = pd.read_csv(file_name,parse_dates=[0])
clean_df

,timestamp,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,SpO2,qos
0,2017-05-25 03:56:16.760,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2723, 2807, 2874, 2925, 2961, 2985, 2994, 299...",NaN,1
1,2017-05-25 03:56:17.016,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1718, 1695, 1673, 1652, 1611, 1560, 1524, 149...",NaN,1
2,2017-05-25 03:56:17.272,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1208, 1320, 1460, 1621, 1771, 1914, 2071, 222...",NaN,1
3,2017-05-25 03:56:17.528,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2191, 2102, 2015, 1933, 1859, 1794, 1737, 168...",NaN,1
4,2017-05-25 03:56:17.784,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1173, 1147, 1119, 1097, 1079, 1062, 1053, 106...",NaN,1
5,2017-05-25 03:56:18.040,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2849, 2809, 2762, 2707, 2643, 2570, 2490, 240...",NaN,1
6,2017-05-25 03:56:18.296,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1397, 1382, 1368, 1350, 1330, 1309, 1287, 126...",NaN,1
7,2017-05-25 03:56:18.552,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2914, 2934, 2943, 2942, 2933, 2917, 2894, 286...",NaN,1
8,2017-05-25 03:56:18.680,NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,96.7,1
9,2017-05-25 03:56:18.712,NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,1
10,2017-05-25 03:56:18.808,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1521, 1508, 1493, 1476, 1457, 1437, 1416, 139...",NaN,1
11,2017-05-25 03:56:19.064,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2387, 2497, 2589, 2664, 2746, 2819, 2861, 288...",NaN,1
12,2017-05-25 03:56:19.320,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1600, 1568, 1540, 1515, 1493, 1472, 1452, 143...",NaN,1
13,2017-05-25 03:56:19.576,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1310, 1458, 1621, 1769, 1906, 2053, 2194, 232...",NaN,1
14,2017-05-25 03:56:19.736,NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,96.5,1
15,2017-05-25 03:56:19.832,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1933, 1849, 1772, 1703, 1642, 1590, 1546, 150...",NaN,1
16,2017-05-25 03:56:20.088,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[963, 941, 935, 947, 980, 1042, 1135, 1258, 14...",NaN,1
17,2017-05-25 03:56:20.344,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2408, 2338, 2260, 2176, 2087, 1997, 1909, 183...",NaN,1
18,2017-05-25 03:56:20.600,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1113, 1098, 1076, 1050, 1021, 988, 955, 925, ...",NaN,1
19,2017-05-25 03:56:20.728,NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,96.3,1
20,2017-05-25 03:56:20.760,NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,1
21,2017-05-25 03:56:20.856,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2574, 2553, 2526, 2492, 2451, 2408, 2361, 230...",NaN,1
22,2017-05-25 03:56:21.112,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1279, 1263, 1246, 1227, 1243, 1276, 1281, 127...",NaN,1
23,2017-05-25 03:56:21.368,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2749, 2771, 2784, 2789, 2785, 2775, 2761, 274...",NaN,1
24,2017-05-25 03:56:21.624,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1581, 1564, 1547, 1529, 1511, 1492, 1472, 145...",NaN,1
25,2017-05-25 03:56:21.752,NaN,NaN,"{'mean': 88, 'systolic': 139, 'diastolic': 73}",NaN,96.0,1
26,2017-05-25 03:56:21.784,NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,1
27,2017-05-25 03:56:21.880,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2535, 2591, 2629, 2655, 2677, 2693, 2702, 270...",NaN,1
28,2017-05-25 03:56:22.136,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1609, 1588, 1570, 1552, 1535, 1518, 1501, 148...",NaN,1
29,2017-05-25 03:56:22.392,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2149, 2230, 2307, 2374, 2431, 2477, 251...",NaN,1
...,...,...,...,...,...,...,...
761405,2017-05-27 03:56:04.304,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761406,2017-05-27 03:56:04.560,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761407,2017-05-27 03:56:04.816,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761408,2017-05-27 03:56:04.880,NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,0
761409,2017-05-27 03:56:04.912,NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,0
761410,2017-05-27 03:56:05.072,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761411,2017-05-27 03:56:05.328,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761412,2017-05-27 03:56:05.584,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761413,2017-05-27 03:56:05.840,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761414,2017-05-27 03:56:05.904,NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,0
761415,2017-05-27 03:56:06.096,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761416,2017-05-27 03:56:06.352,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761417,2017-05-27 03:56:06.608,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761418,2017-05-27 03:56:06.864,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761419,2017-05-27 03:56:06.928,NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,0
761420,2017-05-27 03:56:07.120,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761421,2017-05-27 03:56:07.376,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761422,2017-05-27 03:56:07.632,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761423,2017-05-27 03:56:07.888,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761424,2017-05-27 03:56:07.952,NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,0
761425,2017-05-27 03:56:07.984,NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,0
761426,2017-05-27 03:56:08.144,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761427,2017-05-27 03:56:08.400,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761428,2017-05-27 03:56:08.656,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761429,2017-05-27 03:56:08.912,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761430,2017-05-27 03:56:08.976,NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,0
761431,2017-05-27 03:56:09.008,NaN,NaN,"{'mean': None, 'systolic': None, 'diastolic': ...",NaN,NaN,0
761432,2017-05-27 03:56:09.168,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761433,2017-05-27 03:56:09.424,"[-40.96, -40.96, -40.96, -40.96, -40.96, -40.9...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2047, 2047, 2047, 2047, 2047, 2047, 2047, 204...",NaN,0
761434,2017-05-27 03:56:10.000,NaN,NaN,"{'mean': 'Not a number', 'systolic': 'Not a nu...",NaN,NaN,0

## Load and Clean Alarms

* Load alarm data
* Cleaning:
    * Timestamps/timezones

In [9]:
alarms_fname = '../../original_data/5-25-5-26-ecg-alarms.csv'
alarms_df = pd.read_csv(alarms_fname,parse_dates=[0])
alarms_df = alarms_df.set_index("timestamp").tz_localize("UTC").tz_convert('Etc/GMT+4')
alarms_df

                                                                     alarm_type
timestamp
2017-05-25 05:52:54.992000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 05:53:51.312000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 05:58:09.360000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 05:58:10.384000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 06:00:32.720000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 06:00:55.720000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 06:09:29.296000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 09:50:49.584000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 09:56:07.024000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 09:56:08.016000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 10:00:40.400000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 10:24:02.256000-04:00           Clin. SIGNIFICANT EKG alarm (URGENT)
2017-05-25 16:55:49.960000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 22:42:52.264000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 22:46:46.760000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 22:50:12.584000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 23:41:58.496000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-25 23:45:18.176000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 00:58:06.592000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:18:20-04:00         Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:25:06.560000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:28:29.312000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:33:53.888000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 01:43:18.112000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)
2017-05-26 02:10:39.584000-04:00  Clin. INDETERMINATE EKG alarm (INDETERMINATE)

## Putting it together

* Pipeline:
    1. Choose an alarm
    2. Apply it to the orignial dataset
    3. Unpack the dictionary containing non-invasive blood pressure values.

Slice dataframe based on window of time around alarm (isolated_physio_df)

In [10]:
alarms = alarms_df.index.to_pydatetime()
alarms

array([ datetime.datetime(2017, 5, 25, 5, 52, 54, 992000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 5, 53, 51, 312000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 5, 58, 9, 360000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 5, 58, 10, 384000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 6, 0, 32, 720000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 6, 0, 55, 720000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 6, 9, 29, 296000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 9, 50, 49, 584000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 9, 56, 7, 24000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 9, 56, 8, 16000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 10, 0, 40, 400000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 10, 24, 2, 256000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 16, 55, 49, 960000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 22, 42, 52, 264000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 22, 46, 46, 760000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 22, 50, 12, 584000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 23, 41, 58, 496000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 25, 23, 45, 18, 176000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 0, 58, 6, 592000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 18, 20, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 25, 6, 560000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 28, 29, 312000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 33, 53, 888000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 1, 43, 18, 112000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>),
       datetime.datetime(2017, 5, 26, 2, 10, 39, 584000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>)], dtype=object)

In [11]:
len(alarms)

25

In [12]:
alarm = alarms[0]
alarm

datetime.datetime(2017, 5, 25, 5, 52, 54, 992000, tzinfo=<StaticTzInfo 'Etc/GMT+4'>)

In [13]:
for i in range(len(alarms)):
    alarm = alarms[i]
    isolated_df = cleaned_df[alarm - pd.Timedelta("500 seconds"):alarm]
    isolated_df.to_csv("sliced_dataframe.csv" ,  index = True)
    isolated_df = pd.read_csv("sliced_dataframe.csv")
    
    tot_cnt = len(isolated_df)
    # Create a new dataframe indicating "real" alarms
    l = [0 for i in range(tot_cnt - 1)] # 0 indicates NO alarm
    l.append(1)                         # 1 indicates Real alarm
    df = pd.DataFrame(np.array(l), columns = ["Annotated ECG alarm"])
    isolated_df = pd.concat([isolated_df, df], axis = 1)
    
    if (tot_cnt == 0):
        continue
        
    if i == 0:
        sliced_df = isolated_df.copy()
    else:
        sliced_df = pd.concat([sliced_df, isolated_df], axis = 0)

In [14]:
sliced_df

,timestamp,ECG,Heart Rate,Non-invasive Blood Pressure,Pleth,SpO2,qos,Annotated ECG alarm
0,2017-05-25 05:44:35.216000-04:00,"[-0.065000000000004, -0.08000000000000501, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2996, 2986, 2966, 2937, 2901, 2862, 2821, 277...",NaN,1,0
1,2017-05-25 05:44:35.472000-04:00,"[-0.025000000000005, -0.020000000000010003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1775, 1779, 1780, 1777, 1769, 1757, 1741, 172...",NaN,1,0
2,2017-05-25 05:44:35.728000-04:00,"[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1218, 1210, 1201, 1196, 1193, 1186, 1177, 116...",NaN,1,0
3,2017-05-25 05:44:35.792000-04:00,NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,98.5,1,0
4,2017-05-25 05:44:35.984000-04:00,"[0.034999999999989005, 0.009999999999990001, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2972, 2980, 2978, 2967, 2948, 2931, 2913, 288...",NaN,1,0
5,2017-05-25 05:44:36.240000-04:00,"[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1713, 1713, 1714, 1713, 1710, 1704, 1695, 168...",NaN,1,0
6,2017-05-25 05:44:36.496000-04:00,"[-0.140000000000007, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1163, 1150, 1138, 1127, 1116, 1105, 1094, 108...",NaN,1,0
7,2017-05-25 05:44:36.752000-04:00,"[-0.035000000000003, -0.045000000000008006, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2922, 2955, 2981, 2998, 3005, 3002, 2990, 297...",NaN,1,0
8,2017-05-25 05:44:36.816000-04:00,NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,98.5,1,0
9,2017-05-25 05:44:37.008000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1728, 1724, 1723, 1723, 1722, 1721, 1719, 171...",NaN,1,0
10,2017-05-25 05:44:37.264000-04:00,"[-0.160000000000003, -0.170000000000008, -0.17...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1179, 1167, 1156, 1146, 1136, 1127, 1119, 111...",NaN,1,0
11,2017-05-25 05:44:37.520000-04:00,"[-0.135000000000005, -0.135000000000005, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2352, 2495, 2622, 2731, 2810, 2868, 2922, 296...",NaN,1,0
12,2017-05-25 05:44:37.776000-04:00,"[-0.060000000000009004, -0.19500000000000703, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1850, 1812, 1783, 1762, 1749, 1741, 1738, 173...",NaN,1,0
13,2017-05-25 05:44:37.840000-04:00,NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,98.5,1,0
14,2017-05-25 05:44:38.032000-04:00,"[0.23999999999999402, 0.20999999999999303, 0.1...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1298, 1274, 1256, 1242, 1225, 1217, 1213, 120...",NaN,1,0
15,2017-05-25 05:44:38.288000-04:00,"[-0.14500000000001, -0.14500000000001, -0.1400...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1261, 1387, 1537, 1704, 1881, 2059, 2230, 237...",NaN,1,0
16,2017-05-25 05:44:38.544000-04:00,"[-0.035000000000003, 0.22999999999998902, 0.69...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2322, 2253, 2177, 2101, 2030, 1966, 1911, 186...",NaN,1,0
17,2017-05-25 05:44:38.800000-04:00,"[0.20999999999999303, 0.22999999999998902, 0.2...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1526, 1495, 1465, 1436, 1408, 1381, 1360, 134...",NaN,1,0
18,2017-05-25 05:44:38.864000-04:00,NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,98.4,1,0
19,2017-05-25 05:44:39.056000-04:00,"[-0.120000000000004, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1074, 1078, 1096, 1136, 1204, 1303, 1433, 158...",NaN,1,0
20,2017-05-25 05:44:39.312000-04:00,"[-0.08000000000000501, -0.08000000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2606, 2541, 2470, 2393, 2320, 2249, 2170, 209...",NaN,1,0
21,2017-05-25 05:44:39.568000-04:00,"[0.049999999999990004, 0.06499999999999001, 0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1625, 1598, 1569, 1539, 1508, 1477, 1445, 141...",NaN,1,0
22,2017-05-25 05:44:39.824000-04:00,"[-0.140000000000007, -0.140000000000007, -0.13...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1064, 1049, 1039, 1032, 1024, 1024, 1038, 107...",NaN,1,0
23,2017-05-25 05:44:39.888000-04:00,NaN,75.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,98.4,1,0
24,2017-05-25 05:44:40.080000-04:00,"[-0.09000000000001, -0.09000000000001, -0.0900...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2938, 2896, 2851, 2803, 2750, 2689, 2620, 254...",NaN,1,0
25,2017-05-25 05:44:40.336000-04:00,"[-0.040000000000006, -0.030000000000008003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1712, 1701, 1688, 1671, 1650, 1627, 1602, 157...",NaN,1,0
26,2017-05-25 05:44:40.592000-04:00,"[-0.14500000000001, -0.140000000000007, -0.140...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1112, 1105, 1097, 1088, 1077, 1064, 1055, 104...",NaN,1,0
27,2017-05-25 05:44:40.848000-04:00,"[-0.060000000000009004, -0.08000000000000501, ...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[3034, 3017, 2994, 2964, 2928, 2888, 2844, 279...",NaN,1,0
28,2017-05-25 05:44:40.912000-04:00,NaN,76.0,"{'mean': 89, 'systolic': 134, 'diastolic': 74}",NaN,98.3,1,0
29,2017-05-25 05:44:41.104000-04:00,"[-0.10000000000000801, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[1754, 1752, 1747, 1738, 1725, 1712, 1698, 168...",NaN,1,0
...,...,...,...,...,...,...,...,...
2432,2017-05-26 02:10:33.544000-04:00,"[0.16999999999999402, 0.194999999999993, 0.214...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2433,2017-05-26 02:10:33.800000-04:00,"[-0.165000000000006, -0.170000000000008, -0.19...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2434,2017-05-26 02:10:33.832000-04:00,NaN,83.0,"{'mean': 78, 'systolic': 105, 'diastolic': 69}",NaN,NaN,0,0
2435,2017-05-26 02:10:34.056000-04:00,"[-0.320000000000007, -0.38000000000000905, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2436,2017-05-26 02:10:34.312000-04:00,"[0.14499999999999602, 0.104999999999989, 0.064...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2437,2017-05-26 02:10:34.568000-04:00,"[-0.140000000000007, -0.11500000000000901, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2438,2017-05-26 02:10:34.824000-04:00,"[-0.10500000000000301, -0.10000000000000801, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2439,2017-05-26 02:10:34.856000-04:00,NaN,83.0,"{'mean': 78, 'systolic': 105, 'diastolic': 69}",NaN,NaN,0,0
2440,2017-05-26 02:10:35.080000-04:00,"[-0.19500000000000703, -0.19500000000000703, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2441,2017-05-26 02:10:35.336000-04:00,"[-0.10000000000000801, -0.120000000000004, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2442,2017-05-26 02:10:35.592000-04:00,"[0.059999999999995, 0.059999999999995, 0.05999...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2443,2017-05-26 02:10:35.848000-04:00,"[-0.170000000000008, -0.165000000000006, -0.15...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2444,2017-05-26 02:10:35.880000-04:00,NaN,83.0,"{'mean': 78, 'systolic': 105, 'diastolic': 69}",NaN,NaN,0,0
2445,2017-05-26 02:10:36.104000-04:00,"[0.454999999999991, 0.649999999999991, 0.79999...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2446,2017-05-26 02:10:36.360000-04:00,"[0.31499999999999, 0.31499999999999, 0.3099999...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2447,2017-05-26 02:10:36.616000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2448,2017-05-26 02:10:36.872000-04:00,"[-0.18000000000000602, -0.175000000000004, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2449,2017-05-26 02:10:36.904000-04:00,NaN,83.0,"{'mean': 78, 'systolic': 105, 'diastolic': 69}",NaN,NaN,0,0
2450,2017-05-26 02:10:37.128000-04:00,"[-0.175000000000004, -0.19500000000000703, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2451,2017-05-26 02:10:37.384000-04:00,"[-0.135000000000005, -0.11000000000000601, -0....",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2452,2017-05-26 02:10:37.640000-04:00,"[-0.045000000000008006, -0.030000000000008003,...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2453,2017-05-26 02:10:37.896000-04:00,"[-0.035000000000003, -0.030000000000008003, -0...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2454,2017-05-26 02:10:37.928000-04:00,NaN,84.0,"{'mean': 78, 'systolic': 105, 'diastolic': 69}",NaN,NaN,0,0
2455,2017-05-26 02:10:38.152000-04:00,"[0.31499999999999, 0.304999999999992, 0.289999...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2456,2017-05-26 02:10:38.408000-04:00,"[0.249999999999992, 0.25999999999999, 0.274999...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2457,2017-05-26 02:10:38.664000-04:00,"[-0.10500000000000301, -0.09500000000000501, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2458,2017-05-26 02:10:38.920000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2459,2017-05-26 02:10:38.952000-04:00,NaN,85.0,"{'mean': 78, 'systolic': 105, 'diastolic': 69}",NaN,NaN,0,0
2460,2017-05-26 02:10:39.176000-04:00,"[0.20499999999999102, 0.21499999999999603, 0.2...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0
2461,2017-05-26 02:10:39.432000-04:00,"[-0.175000000000004, -0.175000000000004, -0.18...",NaN,"{'mean': None, 'systolic': None, 'diastolic': ...","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,1

In [15]:
sliced_df[["diastolic_bp","mean_bp","systolic_bp"]] = sliced_df["Non-invasive Blood Pressure"].apply(lambda x : dict(eval(x))).apply(pd.Series )
sliced_df = sliced_df.drop("Non-invasive Blood Pressure", axis=1)
sliced_df

,timestamp,ECG,Heart Rate,Pleth,SpO2,qos,Annotated ECG alarm,diastolic_bp,mean_bp,systolic_bp
0,2017-05-25 05:44:35.216000-04:00,"[-0.065000000000004, -0.08000000000000501, -0....",NaN,"[2996, 2986, 2966, 2937, 2901, 2862, 2821, 277...",NaN,1,0,None,None,None
1,2017-05-25 05:44:35.472000-04:00,"[-0.025000000000005, -0.020000000000010003, -0...",NaN,"[1775, 1779, 1780, 1777, 1769, 1757, 1741, 172...",NaN,1,0,None,None,None
2,2017-05-25 05:44:35.728000-04:00,"[-0.120000000000004, -0.11500000000000901, -0....",NaN,"[1218, 1210, 1201, 1196, 1193, 1186, 1177, 116...",NaN,1,0,None,None,None
3,2017-05-25 05:44:35.792000-04:00,NaN,75.0,NaN,98.5,1,0,74,89,134
4,2017-05-25 05:44:35.984000-04:00,"[0.034999999999989005, 0.009999999999990001, -...",NaN,"[2972, 2980, 2978, 2967, 2948, 2931, 2913, 288...",NaN,1,0,None,None,None
5,2017-05-25 05:44:36.240000-04:00,"[-0.08000000000000501, -0.08000000000000501, -...",NaN,"[1713, 1713, 1714, 1713, 1710, 1704, 1695, 168...",NaN,1,0,None,None,None
6,2017-05-25 05:44:36.496000-04:00,"[-0.140000000000007, -0.135000000000005, -0.13...",NaN,"[1163, 1150, 1138, 1127, 1116, 1105, 1094, 108...",NaN,1,0,None,None,None
7,2017-05-25 05:44:36.752000-04:00,"[-0.035000000000003, -0.045000000000008006, -0...",NaN,"[2922, 2955, 2981, 2998, 3005, 3002, 2990, 297...",NaN,1,0,None,None,None
8,2017-05-25 05:44:36.816000-04:00,NaN,75.0,NaN,98.5,1,0,74,89,134
9,2017-05-25 05:44:37.008000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"[1728, 1724, 1723, 1723, 1722, 1721, 1719, 171...",NaN,1,0,None,None,None
10,2017-05-25 05:44:37.264000-04:00,"[-0.160000000000003, -0.170000000000008, -0.17...",NaN,"[1179, 1167, 1156, 1146, 1136, 1127, 1119, 111...",NaN,1,0,None,None,None
11,2017-05-25 05:44:37.520000-04:00,"[-0.135000000000005, -0.135000000000005, -0.13...",NaN,"[2352, 2495, 2622, 2731, 2810, 2868, 2922, 296...",NaN,1,0,None,None,None
12,2017-05-25 05:44:37.776000-04:00,"[-0.060000000000009004, -0.19500000000000703, ...",NaN,"[1850, 1812, 1783, 1762, 1749, 1741, 1738, 173...",NaN,1,0,None,None,None
13,2017-05-25 05:44:37.840000-04:00,NaN,75.0,NaN,98.5,1,0,74,89,134
14,2017-05-25 05:44:38.032000-04:00,"[0.23999999999999402, 0.20999999999999303, 0.1...",NaN,"[1298, 1274, 1256, 1242, 1225, 1217, 1213, 120...",NaN,1,0,None,None,None
15,2017-05-25 05:44:38.288000-04:00,"[-0.14500000000001, -0.14500000000001, -0.1400...",NaN,"[1261, 1387, 1537, 1704, 1881, 2059, 2230, 237...",NaN,1,0,None,None,None
16,2017-05-25 05:44:38.544000-04:00,"[-0.035000000000003, 0.22999999999998902, 0.69...",NaN,"[2322, 2253, 2177, 2101, 2030, 1966, 1911, 186...",NaN,1,0,None,None,None
17,2017-05-25 05:44:38.800000-04:00,"[0.20999999999999303, 0.22999999999998902, 0.2...",NaN,"[1526, 1495, 1465, 1436, 1408, 1381, 1360, 134...",NaN,1,0,None,None,None
18,2017-05-25 05:44:38.864000-04:00,NaN,75.0,NaN,98.4,1,0,74,89,134
19,2017-05-25 05:44:39.056000-04:00,"[-0.120000000000004, -0.11500000000000901, -0....",NaN,"[1074, 1078, 1096, 1136, 1204, 1303, 1433, 158...",NaN,1,0,None,None,None
20,2017-05-25 05:44:39.312000-04:00,"[-0.08000000000000501, -0.08000000000000501, -...",NaN,"[2606, 2541, 2470, 2393, 2320, 2249, 2170, 209...",NaN,1,0,None,None,None
21,2017-05-25 05:44:39.568000-04:00,"[0.049999999999990004, 0.06499999999999001, 0....",NaN,"[1625, 1598, 1569, 1539, 1508, 1477, 1445, 141...",NaN,1,0,None,None,None
22,2017-05-25 05:44:39.824000-04:00,"[-0.140000000000007, -0.140000000000007, -0.13...",NaN,"[1064, 1049, 1039, 1032, 1024, 1024, 1038, 107...",NaN,1,0,None,None,None
23,2017-05-25 05:44:39.888000-04:00,NaN,75.0,NaN,98.4,1,0,74,89,134
24,2017-05-25 05:44:40.080000-04:00,"[-0.09000000000001, -0.09000000000001, -0.0900...",NaN,"[2938, 2896, 2851, 2803, 2750, 2689, 2620, 254...",NaN,1,0,None,None,None
25,2017-05-25 05:44:40.336000-04:00,"[-0.040000000000006, -0.030000000000008003, -0...",NaN,"[1712, 1701, 1688, 1671, 1650, 1627, 1602, 157...",NaN,1,0,None,None,None
26,2017-05-25 05:44:40.592000-04:00,"[-0.14500000000001, -0.140000000000007, -0.140...",NaN,"[1112, 1105, 1097, 1088, 1077, 1064, 1055, 104...",NaN,1,0,None,None,None
27,2017-05-25 05:44:40.848000-04:00,"[-0.060000000000009004, -0.08000000000000501, ...",NaN,"[3034, 3017, 2994, 2964, 2928, 2888, 2844, 279...",NaN,1,0,None,None,None
28,2017-05-25 05:44:40.912000-04:00,NaN,76.0,NaN,98.3,1,0,74,89,134
29,2017-05-25 05:44:41.104000-04:00,"[-0.10000000000000801, -0.10000000000000801, -...",NaN,"[1754, 1752, 1747, 1738, 1725, 1712, 1698, 168...",NaN,1,0,None,None,None
...,...,...,...,...,...,...,...,...,...,...
2432,2017-05-26 02:10:33.544000-04:00,"[0.16999999999999402, 0.194999999999993, 0.214...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2433,2017-05-26 02:10:33.800000-04:00,"[-0.165000000000006, -0.170000000000008, -0.19...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2434,2017-05-26 02:10:33.832000-04:00,NaN,83.0,NaN,NaN,0,0,69,78,105
2435,2017-05-26 02:10:34.056000-04:00,"[-0.320000000000007, -0.38000000000000905, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2436,2017-05-26 02:10:34.312000-04:00,"[0.14499999999999602, 0.104999999999989, 0.064...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2437,2017-05-26 02:10:34.568000-04:00,"[-0.140000000000007, -0.11500000000000901, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2438,2017-05-26 02:10:34.824000-04:00,"[-0.10500000000000301, -0.10000000000000801, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2439,2017-05-26 02:10:34.856000-04:00,NaN,83.0,NaN,NaN,0,0,69,78,105
2440,2017-05-26 02:10:35.080000-04:00,"[-0.19500000000000703, -0.19500000000000703, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2441,2017-05-26 02:10:35.336000-04:00,"[-0.10000000000000801, -0.120000000000004, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2442,2017-05-26 02:10:35.592000-04:00,"[0.059999999999995, 0.059999999999995, 0.05999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2443,2017-05-26 02:10:35.848000-04:00,"[-0.170000000000008, -0.165000000000006, -0.15...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2444,2017-05-26 02:10:35.880000-04:00,NaN,83.0,NaN,NaN,0,0,69,78,105
2445,2017-05-26 02:10:36.104000-04:00,"[0.454999999999991, 0.649999999999991, 0.79999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2446,2017-05-26 02:10:36.360000-04:00,"[0.31499999999999, 0.31499999999999, 0.3099999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2447,2017-05-26 02:10:36.616000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2448,2017-05-26 02:10:36.872000-04:00,"[-0.18000000000000602, -0.175000000000004, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2449,2017-05-26 02:10:36.904000-04:00,NaN,83.0,NaN,NaN,0,0,69,78,105
2450,2017-05-26 02:10:37.128000-04:00,"[-0.175000000000004, -0.19500000000000703, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2451,2017-05-26 02:10:37.384000-04:00,"[-0.135000000000005, -0.11000000000000601, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2452,2017-05-26 02:10:37.640000-04:00,"[-0.045000000000008006, -0.030000000000008003,...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2453,2017-05-26 02:10:37.896000-04:00,"[-0.035000000000003, -0.030000000000008003, -0...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2454,2017-05-26 02:10:37.928000-04:00,NaN,84.0,NaN,NaN,0,0,69,78,105
2455,2017-05-26 02:10:38.152000-04:00,"[0.31499999999999, 0.304999999999992, 0.289999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2456,2017-05-26 02:10:38.408000-04:00,"[0.249999999999992, 0.25999999999999, 0.274999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2457,2017-05-26 02:10:38.664000-04:00,"[-0.10500000000000301, -0.09500000000000501, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2458,2017-05-26 02:10:38.920000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2459,2017-05-26 02:10:38.952000-04:00,NaN,85.0,NaN,NaN,0,0,69,78,105
2460,2017-05-26 02:10:39.176000-04:00,"[0.20499999999999102, 0.21499999999999603, 0.2...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,0,None,None,None
2461,2017-05-26 02:10:39.432000-04:00,"[-0.175000000000004, -0.175000000000004, -0.18...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,0,1,None,None,None

In [16]:
sliced_df = sliced_df.reindex_axis(["timestamp", "ECG", "Heart Rate", "Pleth", "SpO2", "diastolic_bp","mean_bp","systolic_bp", "qos", "Annotated ECG alarm"], axis=1)
sliced_df

,timestamp,ECG,Heart Rate,Pleth,SpO2,diastolic_bp,mean_bp,systolic_bp,qos,Annotated ECG alarm
0,2017-05-25 05:44:35.216000-04:00,"[-0.065000000000004, -0.08000000000000501, -0....",NaN,"[2996, 2986, 2966, 2937, 2901, 2862, 2821, 277...",NaN,None,None,None,1,0
1,2017-05-25 05:44:35.472000-04:00,"[-0.025000000000005, -0.020000000000010003, -0...",NaN,"[1775, 1779, 1780, 1777, 1769, 1757, 1741, 172...",NaN,None,None,None,1,0
2,2017-05-25 05:44:35.728000-04:00,"[-0.120000000000004, -0.11500000000000901, -0....",NaN,"[1218, 1210, 1201, 1196, 1193, 1186, 1177, 116...",NaN,None,None,None,1,0
3,2017-05-25 05:44:35.792000-04:00,NaN,75.0,NaN,98.5,74,89,134,1,0
4,2017-05-25 05:44:35.984000-04:00,"[0.034999999999989005, 0.009999999999990001, -...",NaN,"[2972, 2980, 2978, 2967, 2948, 2931, 2913, 288...",NaN,None,None,None,1,0
5,2017-05-25 05:44:36.240000-04:00,"[-0.08000000000000501, -0.08000000000000501, -...",NaN,"[1713, 1713, 1714, 1713, 1710, 1704, 1695, 168...",NaN,None,None,None,1,0
6,2017-05-25 05:44:36.496000-04:00,"[-0.140000000000007, -0.135000000000005, -0.13...",NaN,"[1163, 1150, 1138, 1127, 1116, 1105, 1094, 108...",NaN,None,None,None,1,0
7,2017-05-25 05:44:36.752000-04:00,"[-0.035000000000003, -0.045000000000008006, -0...",NaN,"[2922, 2955, 2981, 2998, 3005, 3002, 2990, 297...",NaN,None,None,None,1,0
8,2017-05-25 05:44:36.816000-04:00,NaN,75.0,NaN,98.5,74,89,134,1,0
9,2017-05-25 05:44:37.008000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"[1728, 1724, 1723, 1723, 1722, 1721, 1719, 171...",NaN,None,None,None,1,0
10,2017-05-25 05:44:37.264000-04:00,"[-0.160000000000003, -0.170000000000008, -0.17...",NaN,"[1179, 1167, 1156, 1146, 1136, 1127, 1119, 111...",NaN,None,None,None,1,0
11,2017-05-25 05:44:37.520000-04:00,"[-0.135000000000005, -0.135000000000005, -0.13...",NaN,"[2352, 2495, 2622, 2731, 2810, 2868, 2922, 296...",NaN,None,None,None,1,0
12,2017-05-25 05:44:37.776000-04:00,"[-0.060000000000009004, -0.19500000000000703, ...",NaN,"[1850, 1812, 1783, 1762, 1749, 1741, 1738, 173...",NaN,None,None,None,1,0
13,2017-05-25 05:44:37.840000-04:00,NaN,75.0,NaN,98.5,74,89,134,1,0
14,2017-05-25 05:44:38.032000-04:00,"[0.23999999999999402, 0.20999999999999303, 0.1...",NaN,"[1298, 1274, 1256, 1242, 1225, 1217, 1213, 120...",NaN,None,None,None,1,0
15,2017-05-25 05:44:38.288000-04:00,"[-0.14500000000001, -0.14500000000001, -0.1400...",NaN,"[1261, 1387, 1537, 1704, 1881, 2059, 2230, 237...",NaN,None,None,None,1,0
16,2017-05-25 05:44:38.544000-04:00,"[-0.035000000000003, 0.22999999999998902, 0.69...",NaN,"[2322, 2253, 2177, 2101, 2030, 1966, 1911, 186...",NaN,None,None,None,1,0
17,2017-05-25 05:44:38.800000-04:00,"[0.20999999999999303, 0.22999999999998902, 0.2...",NaN,"[1526, 1495, 1465, 1436, 1408, 1381, 1360, 134...",NaN,None,None,None,1,0
18,2017-05-25 05:44:38.864000-04:00,NaN,75.0,NaN,98.4,74,89,134,1,0
19,2017-05-25 05:44:39.056000-04:00,"[-0.120000000000004, -0.11500000000000901, -0....",NaN,"[1074, 1078, 1096, 1136, 1204, 1303, 1433, 158...",NaN,None,None,None,1,0
20,2017-05-25 05:44:39.312000-04:00,"[-0.08000000000000501, -0.08000000000000501, -...",NaN,"[2606, 2541, 2470, 2393, 2320, 2249, 2170, 209...",NaN,None,None,None,1,0
21,2017-05-25 05:44:39.568000-04:00,"[0.049999999999990004, 0.06499999999999001, 0....",NaN,"[1625, 1598, 1569, 1539, 1508, 1477, 1445, 141...",NaN,None,None,None,1,0
22,2017-05-25 05:44:39.824000-04:00,"[-0.140000000000007, -0.140000000000007, -0.13...",NaN,"[1064, 1049, 1039, 1032, 1024, 1024, 1038, 107...",NaN,None,None,None,1,0
23,2017-05-25 05:44:39.888000-04:00,NaN,75.0,NaN,98.4,74,89,134,1,0
24,2017-05-25 05:44:40.080000-04:00,"[-0.09000000000001, -0.09000000000001, -0.0900...",NaN,"[2938, 2896, 2851, 2803, 2750, 2689, 2620, 254...",NaN,None,None,None,1,0
25,2017-05-25 05:44:40.336000-04:00,"[-0.040000000000006, -0.030000000000008003, -0...",NaN,"[1712, 1701, 1688, 1671, 1650, 1627, 1602, 157...",NaN,None,None,None,1,0
26,2017-05-25 05:44:40.592000-04:00,"[-0.14500000000001, -0.140000000000007, -0.140...",NaN,"[1112, 1105, 1097, 1088, 1077, 1064, 1055, 104...",NaN,None,None,None,1,0
27,2017-05-25 05:44:40.848000-04:00,"[-0.060000000000009004, -0.08000000000000501, ...",NaN,"[3034, 3017, 2994, 2964, 2928, 2888, 2844, 279...",NaN,None,None,None,1,0
28,2017-05-25 05:44:40.912000-04:00,NaN,76.0,NaN,98.3,74,89,134,1,0
29,2017-05-25 05:44:41.104000-04:00,"[-0.10000000000000801, -0.10000000000000801, -...",NaN,"[1754, 1752, 1747, 1738, 1725, 1712, 1698, 168...",NaN,None,None,None,1,0
...,...,...,...,...,...,...,...,...,...,...
2432,2017-05-26 02:10:33.544000-04:00,"[0.16999999999999402, 0.194999999999993, 0.214...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2433,2017-05-26 02:10:33.800000-04:00,"[-0.165000000000006, -0.170000000000008, -0.19...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2434,2017-05-26 02:10:33.832000-04:00,NaN,83.0,NaN,NaN,69,78,105,0,0
2435,2017-05-26 02:10:34.056000-04:00,"[-0.320000000000007, -0.38000000000000905, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2436,2017-05-26 02:10:34.312000-04:00,"[0.14499999999999602, 0.104999999999989, 0.064...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2437,2017-05-26 02:10:34.568000-04:00,"[-0.140000000000007, -0.11500000000000901, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2438,2017-05-26 02:10:34.824000-04:00,"[-0.10500000000000301, -0.10000000000000801, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2439,2017-05-26 02:10:34.856000-04:00,NaN,83.0,NaN,NaN,69,78,105,0,0
2440,2017-05-26 02:10:35.080000-04:00,"[-0.19500000000000703, -0.19500000000000703, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2441,2017-05-26 02:10:35.336000-04:00,"[-0.10000000000000801, -0.120000000000004, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2442,2017-05-26 02:10:35.592000-04:00,"[0.059999999999995, 0.059999999999995, 0.05999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2443,2017-05-26 02:10:35.848000-04:00,"[-0.170000000000008, -0.165000000000006, -0.15...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2444,2017-05-26 02:10:35.880000-04:00,NaN,83.0,NaN,NaN,69,78,105,0,0
2445,2017-05-26 02:10:36.104000-04:00,"[0.454999999999991, 0.649999999999991, 0.79999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2446,2017-05-26 02:10:36.360000-04:00,"[0.31499999999999, 0.31499999999999, 0.3099999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2447,2017-05-26 02:10:36.616000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2448,2017-05-26 02:10:36.872000-04:00,"[-0.18000000000000602, -0.175000000000004, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2449,2017-05-26 02:10:36.904000-04:00,NaN,83.0,NaN,NaN,69,78,105,0,0
2450,2017-05-26 02:10:37.128000-04:00,"[-0.175000000000004, -0.19500000000000703, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2451,2017-05-26 02:10:37.384000-04:00,"[-0.135000000000005, -0.11000000000000601, -0....",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2452,2017-05-26 02:10:37.640000-04:00,"[-0.045000000000008006, -0.030000000000008003,...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2453,2017-05-26 02:10:37.896000-04:00,"[-0.035000000000003, -0.030000000000008003, -0...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2454,2017-05-26 02:10:37.928000-04:00,NaN,84.0,NaN,NaN,69,78,105,0,0
2455,2017-05-26 02:10:38.152000-04:00,"[0.31499999999999, 0.304999999999992, 0.289999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2456,2017-05-26 02:10:38.408000-04:00,"[0.249999999999992, 0.25999999999999, 0.274999...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2457,2017-05-26 02:10:38.664000-04:00,"[-0.10500000000000301, -0.09500000000000501, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2458,2017-05-26 02:10:38.920000-04:00,"[-0.15000000000000502, -0.15000000000000502, -...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2459,2017-05-26 02:10:38.952000-04:00,NaN,85.0,NaN,NaN,69,78,105,0,0
2460,2017-05-26 02:10:39.176000-04:00,"[0.20499999999999102, 0.21499999999999603, 0.2...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,0
2461,2017-05-26 02:10:39.432000-04:00,"[-0.175000000000004, -0.175000000000004, -0.18...",NaN,"[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",NaN,None,None,None,0,1

## Next step

Data preparation for Goal #2 (as described in project description)

Import annotations file:
   1. import window annotations for both PPG and ECG signal
   2. import qos annotations for PPG signal